### PR TITLE
Add support for building AWS EC2 AMIs

### PR DESCRIPTION
**Pull request by cevich**
Certain podman and aardvark-dns CI testing requires capabilities
not available in GCE.  Respectively, executing on bare-metal and on the
arm64 architecture.

* Add the necessary `Makefile` targets, packer definitions, script,
  and CI updates to produce AWS images.
* Add the `gvproxy` package to Fedora images to support testing the
  `podman-machine` command.
* Increase the build timeout since AWS is considerably slower and more
  failure-prone than GCE.
* Update documentation to reflect how both GCE and EC2 images are built.

**N/B:** It was decided that AWS functionality in CI is urgently needed.  While PR is possibly at the "good enough" stage for merging, there are some significant TODO's introduced:

0. Cirrus-CI is currently freaking out and adding a *crap ton* of Dockerfile code annotations that are irreverent.  You can turn them off in the github UI under the `...` menu for each file.
1. A unique AMI ID is produced for `fedora-aws Cache Image` and `fedora-netavark-aws Cache Image`.  These need to be manually extracted from the output logs (or `manifest.json` artifact).  The image ID posted by github-actions bot *only* applies to GCE images.
2. Building AWS EC2 AMI's is vastly more complex than GCE.  There are a *TON* of gotchas and non-obvious configurations.  I have attempted to document & comment most of these but it's not 100% complete.
3. The AWS builds sometimes timeout/fail/break for strange reasons, occasionally leaving running instances behind :angry: Some hand-holding of the build tasks is needed, including cleanup of leftover instances.  In particular the `m5zn.metal` instances - they cost $4/hour to leave running.
4. This PR is producing updated (GCE) Ubuntu 2204 images, but CI is currently broken for a number of tests.  See https://github.com/containers/buildah/pull/4074 https://github.com/containers/podman/pull/14397 and https://github.com/containers/podman/pull/14719

### CODE REVIEW

**Comment by cevich** [comment]
@edsantiago @baude @lsm5 PTAL (I know it's a lot).  I'd like to get this in today or early tomorrow since I'll be on PTO next week.  Hopefully I've not made too many egregious gaffs :confused:

**Comment by cevich** [comment]
Re: failing ubuntu repos.  I opened #143 in case it becomes a problem, it will provide a way to easily bypass that build.

**Comment by cevich** [comment]
Note to me: Latest podman image `ami-06a41d8a81ab56afa`.

**Review by lsm5 — APPROVED** [review]
LGTM, in my limited experience :neutral_face:

**Comment by cevich** [comment]
Thanks for taking a look @lsm5 I know it's a lot :disappointed: 

I'm just going to merge this then.  Any problems can be addressed in future PRs.

**Pull request merged**
