### PR TITLE
Bump automation library version

### PR DESCRIPTION
**Pull request by cevich**
Importantly, this contains a necessary fix for `build_push.sh` needed to stop immutable-image existence-check failing on build (c/image_build cron job).

### CODE REVIEW

**Comment by edsantiago** [comment]
LGTM. I assume this addresses the issue you reported in your `cron build failure` email of `14:19:37 -0400` yesterday?

**Comment by cevich** [comment]
> LGTM. I assume this addresses the issue

Thanks, and yes.

**Comment by edsantiago** [comment]
@cevich #340 has merged, please rebase when you fix the CI failures here

**Comment by cevich** [comment]
Ugh, that `Build IMGTS` keeps flaking for some reason.  In #349 other Fedora-based container image builds are flaking/timing out.  Must be problems with the repos :disappointed:

**Comment by edsantiago** [comment]
Oops, I missed the `c202` email. Package diffs below, I'm not seeing anything worrisome:

- 20240424t143933z-f39f38d13
- 20240411t124913z-f39f38d13 &#x21D1; (built in #340)

|  |*debian*|*prior-fedora*|*fedora*|*fedora-aws*|*rawhide*|
|----|----|----|----|----|----|
|*base*         | 13.1            | 38-1.6          | 39-1.5          | ?               | 41-0            |
|               | 13&nbsp;&#x21D1; |                |                |                |                |
|*kernel*       | 6.7.9-2         | 6.8.7-100       | 6.8.7-200       | 6.8.7-200       | 6.9.0-0.rc5.44  |
|               |                | 6.8.4-100&nbsp;&#x21D1; | 6.8.5-200&nbsp;&#x21D1; | 6.8.4-200&nbsp;&#x21D1; | 6.9.0-0.rc3.30&nbsp;&#x21D1; |
|*grub2-common* | 2.12-2          | 2.06-116        | 2.06-120        | 2.06-118        | 2.06-121        |
|               |                |                | 2.06-118&nbsp;&#x21D1; |                | 2.06-119&nbsp;&#x21D1; |
|*aardvark-dns* | 1.4.0-5         | 1.10.0-1        | 1.10.0-1        | 1.10.0-1        | 1.10.0-1        |
|               |                |                |                |                |                |
|*netavark*     | 1.4.0-4         | 1.10.3-1        | 1.10.3-1        | 1.10.3-1        | 1.10.3-3        |
|               |                |                |                |                |                |
|*buildah*      | 1.33.7+ds1-1    | 1.35.3-1        | 1.35.3-1        | 1.35.3-1        | 1.35.3-1        |
|               |                |                |                |                |                |
|*conmon*       | 2.1.10+ds1-1+b1 | 2.1.10-1        | 2.1.10-1        | 2.1.10-1        | 2.1.10-1        |
|               |                |                |                |                |                |
|*container-selinux*| ?               | 2.230.0-1       | 2.230.0-1       | 2.230.0-1       | 2.230.0-1       |
|               |                |                |                |                |                |
|*containers-common*| ?               | 1-89            | 1-99            | 1-99            | 0.58.0-18       |
|               |                |                |                |                | 0.58.0-8&nbsp;&#x21D1; |
|*criu*         | 3.17.1-3        | 3.18-1          | 3.19-2          | 3.19-2          | 3.19-4          |
|               |                |                |                |                |                |
|*crun*         | 1.14.4-1        | 1.14.4-1        | 1.14.4-1        | 1.14.4-1        | 1.14.4-5        |
|               |                |                |                |                |                |
|*golang*       | 2:1.22~3        | 1.21.9-1        | 1.21.9-1        | 1.21.9-1        | 1.22.2-3        |
|               |                | 1.21.8-1&nbsp;&#x21D1; |                |                |                |
|*gvisor-tap-vsock*| ?               | 0.7.3-1         | 0.7.3-1         | 0.7.3-1         | 0.7.3-2         |
|               |                |                |                |                |                |
|*nmap-ncat*    | 7.94+git20230807.3be01efb1+dfsg-3+b1 | 7.93-2          | 7.95-1          | 7.94-1          | 7.94-1          |
|               |                |                | 7.94-1&nbsp;&#x21D1; |                |                |
|*passt*        | 2024-03-26      | 2024-04-05      | 2024-04-05      | 2024-04-05      | 2024-04-05      |
|               |                |                |                |                |                |
|*podman*       | 4.9.4+ds1-1     | 4.9.4-1         | 4.9.4-1         | 4.9.4-1         | 5.0.1-1         |
|               |                |                |                |                |                |
|*runc*         | 1.1.12+ds1-2    | 1.1.12-1        | 1.1.12-1        | 1.1.12-1        | 1.1.12-3        |
|               |                |                |                |                |                |
|*skopeo*       | 1.13.3+ds1-2+b1 | 1.15.0-1        | 1.15.0-1        | 1.15.0-1        | 1.15.0-1        |
|               |                |                |                |                |                |
|*slirp4netns*  | 1.2.1-1+b1      | 1.2.2-1         | 1.2.2-1         | 1.2.2-1         | 1.2.2-2         |
|               |                |                |                |                |                |
|*systemd*      | 255.4-1+b1      | 253.17-1        | 254.10-1        | 254.10-1        | 255.4-1         |
|               |                |                |                |                |                |
|*tar*          | 1.34+dfsg-1.2+deb12u1 | 1.34-8          | 1.35-2          | 1.35-2          | 1.35-3          |
|               |                |                |                |                |                |

**Comment by cevich** [comment]
Thanks Ed, no worries.  I just needed the build-push VM image to fix our ailing 'immutable' builds.  The real interesting stuff is going to be in https://github.com/containers/automation_images/pull/349

**Pull request merged**
