### PR TITLE
Update ubuntu base + refresh all packages

### PR DESCRIPTION
**Pull request by cevich**
Signed-off-by: Chris Evich <cevich@redhat.com>

### CODE REVIEW

**Comment by giuseppe** [comment]
@cevich can we get fresher images? :-)

**Comment by cevich** [comment]
> @cevich can we get fresher images? :-)

Yep, building them now.  Assuming it completes successfully, the new image ID will be automatically posted in a PR comment.

**Comment by giuseppe** [comment]
looks like there was a failure :/

**Comment by cevich** [comment]
Oof, I was afraid I might hit that.  Fix is easy-ish though...

**Comment by cevich** [comment]
...k, that should fix it.

**Comment by cevich** [comment]
Just a boring rebase, so I manually canceled the image build.

**Pull request merged**
