### PR TITLE
Build-Push: Install pip and wait-for-copr

### PR DESCRIPTION
**Pull request by lsm5**
Podman-Desktop team would like fcos images built with packages from rhcontainerbot/podman-next for MacOS testing with the latest unreleased bits.
Ref: https://github.com/containers/podman/pull/19477

This commit installs pip and wait-for-copr in the build-push images. wait-for-copr, as the name suggests, waits for a build with a specified string to become available on a copr repo.
Ref: https://github.com/packit/wait-for-copr

### CODE REVIEW

**Review by cevich — APPROVED** [review]
LGTM

**Comment by cevich** [comment]
oh, you need to `make IMG_SFX` and add that file too.  Otherwise validate will fail.

**Comment by lsm5** [comment]
> oh, you need to `make IMG_SFX` and add that file too. Otherwise validate will fail.

done.

**Review by cevich — CHANGES_REQUESTED** [review]
Ooooo, [spotted a problem](https://cirrus-ci.com/task/4889332679442432?logs=main#L526) (glad I looked at the build log):

```
    build-push: 
  WARNING: The script wait-for-copr is installed in '/home/packer/.local/bin' which is not on PATH.
    build-push:   Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
```

I think maybe stick a `$SUDO` in front of the `pip3` and that should stick it somewhere more generally usable?

**Comment by cevich** [comment]
oh, and you'll want to rebase since I just merged a PR.

**Review by cevich — APPROVED** [review]
LGTM.  Maybe try this out in your podman PR, then if the image is okay, just go ahead and merge this.

One (maybe) minor thing of note (in case anybody goes hunting through PRs), [I don't remember seeing this before](https://cirrus-ci.com/task/4620025076645888?logs=main#L539-L527) (I could be mistaken):

```
    build-push: 
The unit files have no installation config (WantedBy=, RequiredBy=, Also=,
    build-push: 
Alias= settings in the [Install] section, and DefaultInstance= for template
    build-push: 
units). This means they are not meant to be enabled or disabled using systemctl.
    build-push: 
 
    build-push: 
Possible reasons for having this kind of units are:
    build-push: 
• A unit may be statically enabled by being symlinked from another unit's
    build-push: 
  .wants/ or .requires/ directory.
    build-push: 
• A unit's purpose may be to act as a helper for some other unit which has
    build-push: 
  a requirement dependency on it.
    build-push: 
• A unit may be started when needed via activation (socket, path, timer,
    build-push: 
  D-Bus, udev, scripted systemctl call, ...).
    build-push: 
• In case of template units, the unit is meant to be enabled with some
    build-push: 
  instance name specified.
```

**Comment by cevich** [comment]
Oof, need one more rebase.

**Comment by cevich** [comment]
Clarificatin: Rebase + run `make IMG_SFX` again (and commit).

**Comment by cevich** [comment]
Commit moved into https://github.com/containers/automation_images/pull/294

**Pull request closed without merging**
