### PR TITLE
Add zstd on windows

### PR DESCRIPTION
**Pull request by Luap99**
windows: add zstandard package
Windows does not have zstd by default so we need to install it. In
particular I am looking at switching the repo archive to zstd as this
makes things much faster (over 1min in podman)[1] but the windows
testing is unable to extract that. While archiver added zstd support a
while back it is not in the version that is on chocolatey which seems a
bit out of date.

[1] https://github.com/containers/podman/pull/24120

Build new images

Bump debian tar timebomb, remove manual crun install as the package is
stable now and most importantly remove IMA workaround as the issue[1],
we will see if that is true.

[1] https://github.com/containers/podman/issues/18543

### CODE REVIEW

**Comment by edsantiago** [comment]
- 20241010t105554z-f40f39d13
- 20240911t151000z-f40f39d13 &#x21D1; (built in #386)

|  |*debian*|*prior-fedora*|*fedora*|*fedora-aws*|*rawhide*|
|----|----|----|----|----|----|
|*kernel*       | 6.11.2-1        | 6.5.6-300       | 6.8.5-301       | 6.8.5-301       | 6.8.5-301       |
|               | 6.10.9-1&nbsp;&#x21D1; |                |                |                |                |
|*grub2-common* | 2.12-5          | 2.06-121        | 2.06-123        | 2.06-123        | 2.12-7          |
|               |                |                |                |                | 2.12-4&nbsp;&#x21D1; |
|*aardvark-dns* | 1.12.2-1        | 1.12.2-2        | 1.12.2-2        | 1.12.2-2        | 1.12.2-2        |
|               |                | 1.12.1-1&nbsp;&#x21D1; |                |                |                |
|*buildah*      | 1.37.3+ds1-3    | 1.37.1-1        | 1.37.4-1        | 1.37.3-1        | 1.37.4-1        |
|               | 1.37.2+ds1-3&nbsp;&#x21D1; |                | 1.37.1-1&nbsp;&#x21D1; | 1.37.1-1&nbsp;&#x21D1; | 1.37.2-1&nbsp;&#x21D1; |
|*conmon*       | 2.1.12-1        | 2.1.12-2        | 2.1.12-2        | 2.1.12-2        | 2.1.12-3        |
|               | 2.1.10+ds1-1+b1&nbsp;&#x21D1; | 2.1.12-1&nbsp;&#x21D1; |                |                | 2.1.12-2&nbsp;&#x21D1; |
|*container-selinux*| ?               | 2.233.0-1       | 2.233.0-1       | 2.233.0-1       | 2.233.0-1       |
|               |                | 2.232.1-1&nbsp;&#x21D1; | 2.232.1-1&nbsp;&#x21D1; | 2.232.1-1&nbsp;&#x21D1; | 2.232.1-2&nbsp;&#x21D1; |
|*containers-common*| ?               | 1-99            | 0.60.4-1        | 0.60.4-1        | 0.60.4-1        |
|               |                |                | 0.60.1-1&nbsp;&#x21D1; | 0.60.1-1&nbsp;&#x21D1; | 0.60.2-1&nbsp;&#x21D1; |
|*criu*         | 3.17.1-3        | 3.19-2          | 4.0-1           | 3.19-4          | 4.0-1           |
|               |                |                | 3.19-6&nbsp;&#x21D1; |                | 3.19-7&nbsp;&#x21D1; |
|*docker-ce*    | 5:27.3.1-1\~debian.12\~bookworm | ?               | ?               | ?               | ?               |
|               | 5:27.2.1-1\~debian.12\~bookworm&nbsp;&#x21D1; |                |                |                |                |
|*golang*       | 2:1.23\~2       | 1.22.7-3        | 1.22.7-1        | 1.22.7-1        | 1.23.2-2        |
|               | 2:1.22\~3&nbsp;&#x21D1; | 1.21.12-1&nbsp;&#x21D1; | 1.22.6-1&nbsp;&#x21D1; | 1.22.6-1&nbsp;&#x21D1; | 1.23.0-2&nbsp;&#x21D1; |
|*gvisor-tap-vsock*| ?               | 0.7.5-1         | ?               | ?               | ?               |
|               |                | 0.7.4-1&nbsp;&#x21D1; |                |                |                |
|*passt*        | 2024-09-06      | 2024-09-06      | 2024-09-06      | 2024-09-06      | 2024-09-06      |
|               |                | 2024-08-14&nbsp;&#x21D1; |                |                |                |
|*podman*       | 5.2.3+ds1-3     | 4.9.4-1         | 5.2.4-1         | 5.2.3-1         | 5.2.4-1         |
|               | 5.2.2+ds1-2&nbsp;&#x21D1; |                | 5.2.2-1&nbsp;&#x21D1; | 5.2.2-1&nbsp;&#x21D1; | 5.2.2-1&nbsp;&#x21D1; |
|*runc*         | 1.1.12+ds1-5+b1 | 1.1.12-1        | 1.1.12-3        | 1.1.12-3        | 1.1.12-4        |
|               | 1.1.12+ds1-5&nbsp;&#x21D1; |                |                |                |                |
|*skopeo*       | 1.16.1+ds1-1    | 1.16.1-1        | 1.16.1-1        | 1.16.1-1        | 1.16.1-2        |
|               | 1.13.3+ds1-2+b2&nbsp;&#x21D1; |                |                |                | 1.16.1-1&nbsp;&#x21D1; |
|*systemd*      | 256.7-1         | 254.18-1        | 255.12-1        | 255.12-1        | 256.5-1         |
|               | 256.6-1&nbsp;&#x21D1; | 254.16-1&nbsp;&#x21D1; | 255.10-3&nbsp;&#x21D1; | 255.10-3&nbsp;&#x21D1; |                |

**Comment by edsantiago** [comment]
Fingers crossed for the `ima` thing

**Comment by Luap99** [comment]
Images are being tested in https://github.com/containers/podman/pull/24227 and https://github.com/containers/podman/pull/24120

**Comment by edsantiago** [comment]
LGTM and is merged into Podman.

@Luap99 should this be tagged for updating the rest of the repos?

**Comment by Luap99** [comment]
Yes sure let's give it go elsewhere

**Pull request merged**
