### PR TITLE
DO NOT MERGE: try new pasta and crun

### PR DESCRIPTION
**Pull request by edsantiago**
passt, for https://github.com/containers/podman/issues/24219

crun, for https://github.com/containers/podman/pull/24327

Do not merge, because:
  1. crun 1.18.1 is buggy, we really want 1.18.2
  2. we really need to focus on #390 (bumping to f41)

Signed-off-by: Ed Santiago <santiago@redhat.com>

### CODE REVIEW

**Comment by Luap99** [comment]
keep in mind f40 will not pass podman CI due a kernel bug https://github.com/containers/podman/issues/24374

so we would need to downgrade the kernel or work around by forcing nftables until the fix landed in the stable fedora kernel

**Comment by edsantiago** [comment]
- 20241104t142134z-f40f39d13
- 20241016t144444z-f40f39d13 &#x21D1; (built in #389)

|  |*debian*|*prior-fedora*|*fedora*|*fedora-aws*|*rawhide*|
|----|----|----|----|----|----|
|*kernel*       | 6.11.5-1        | 6.5.6-300       | 6.8.5-301       | 6.11.5-200      | 6.8.5-301       |
|               | 6.11.2-1&nbsp;&#x21D1; |                |                | 6.8.5-301&nbsp;&#x21D1; |                |
|*grub2-common* | 2.12-5          | 2.06-121        | 2.06-123        | 2.06-123        | 2.12-10         |
|               |                |                |                |                | 2.12-9&nbsp;&#x21D1; |
|*aardvark-dns* | 1.12.2-1        | 1.12.2-2        | 1.13.0-1        | 1.12.2-2        | 1.12.2-2        |
|               |                |                | 1.12.2-2&nbsp;&#x21D1; |                |                |
|*netavark*     | 1.12.1-3        | 1.12.2-1        | 1.13.0-1        | 1.12.2-1        | 1.12.2-1        |
|               |                |                | 1.12.2-1&nbsp;&#x21D1; |                |                |
|*buildah*      | 1.37.5+ds1-1    | 1.37.1-1        | 1.37.5-1        | 1.37.3-1        | 1.37.5-1        |
|               | 1.37.4+ds1-1&nbsp;&#x21D1; |                | 1.37.4-1&nbsp;&#x21D1; |                | 1.37.4-1&nbsp;&#x21D1; |
|*conmon*       | 2.1.12-3        | 2.1.12-2        | 2.1.12-2        | 2.1.12-2        | 2.1.12-3        |
|               | 2.1.12-1&nbsp;&#x21D1; |                |                |                |                |
|*containers-common*| ?               | 1-99            | 0.60.4-2        | 0.60.4-2        | 0.60.4-5        |
|               |                |                | 0.60.4-1&nbsp;&#x21D1; | 0.60.4-1&nbsp;&#x21D1; | 0.60.4-1&nbsp;&#x21D1; |
|*criu*         | 3.17.1-3        | 4.0-1           | 4.0-1           | 4.0-1           | 4.0-2           |
|               |                |                |                |                | 4.0-1&nbsp;&#x21D1; |
|*crun*         | 1.18.2-1        | 1.18-1          | 1.18-1          | 1.18-1          | 1.18.2-1        |
|               | 1.17-1&nbsp;&#x21D1; | 1.17-1&nbsp;&#x21D1; | 1.17-1&nbsp;&#x21D1; | 1.17-1&nbsp;&#x21D1; | 1.17-1&nbsp;&#x21D1; |
|*passt*        | 2024-10-30      | 2024-10-30      | 2024-10-30      | 2024-10-30      | 2024-10-30      |
|               | 2024-09-06&nbsp;&#x21D1; | 2024-09-06&nbsp;&#x21D1; | 2024-09-06&nbsp;&#x21D1; | 2024-09-06&nbsp;&#x21D1; | 2024-09-06&nbsp;&#x21D1; |
|*podman*       | 5.2.5-1         | 4.9.4-1         | 5.2.5-2         | 5.2.3-1         | 5.3.0\~rc2-1    |
|               | 5.2.3+ds1-4&nbsp;&#x21D1; |                | 5.2.4-1&nbsp;&#x21D1; |                | 5.2.4-1&nbsp;&#x21D1; |
|*runc*         | 1.1.15+ds1-1    | 1.1.12-1        | 1.2.1-1         | 1.1.12-3        | 1.2.1-1         |
|               | 1.1.12+ds1-5+b1&nbsp;&#x21D1; |                | 1.1.12-3&nbsp;&#x21D1; |                | 1.1.12-4&nbsp;&#x21D1; |
|*skopeo*       | 1.16.1+ds1-1+b1 | 1.16.1-1        | 1.16.1-1        | 1.16.1-1        | 1.16.1-2        |
|               | 1.16.1+ds1-1&nbsp;&#x21D1; |                |                |                |                |
|*slirp4netns*  | 1.2.1-1+b1      | 1.2.2-1         | 1.3.1-1         | 1.2.2-2         | 1.3.1-1         |
|               |                |                | 1.2.2-2&nbsp;&#x21D1; |                | 1.2.2-3&nbsp;&#x21D1; |
|*systemd*      | 256.7-3         | 254.19-1        | 255.13-1        | 255.13-1        | 256.7-1         |
|               | 256.7-1&nbsp;&#x21D1; | 254.18-1&nbsp;&#x21D1; |                |                |                |

**Comment by edsantiago** [comment]
aws kernel is 6.11.5 and [fails](https://api.cirrus-ci.com/v1/artifact/task/4642122085695488/html/sys-podman-fedora-40-aarch64-root-host-sqlite.log.html). Per Paul on IRC, expected fix is in **6.11.6**.

**Comment by edsantiago** [comment]
Focusing on f41 in #392

**Pull request closed without merging**
