### PR TITLE
Add python3-docker package

### PR DESCRIPTION
**Pull request by cevich**
Signed-off-by: Chris Evich <cevich@redhat.com>

### CODE REVIEW

**Comment by cevich** [comment]
@jwhonce PTAL and add a "approved" github review.  ***NOTE*** Assuming all the tests pass, that will cause this PR to automatically merge.

**Comment by jwhonce** [comment]
LGTM

**Review by jwhonce — APPROVED** [review]

**Comment by cevich** [comment]
mergify retry

**Comment by cevich** [comment]
@Mergifyio refresh

**Pull request merged**
