### PR TITLE
Current fedora is now 41. Bump.

### PR DESCRIPTION
**Pull request by edsantiago**
Signed-off-by: Ed Santiago <santiago@redhat.com>

### CODE REVIEW

**Comment by edsantiago** [comment]
Am fully aware that this will not pick up the new pasta and crun. I'm just expecting this to blow up and require one or more iterations to fix.

**Comment by edsantiago** [comment]
|  |*debian*|*prior-fedora*|*fedora*|*fedora-aws*|*rawhide*|
|----|----|----|----|----|----|
|*base*         | 13.5            | Generic         | Generic-41-1.4  | ?               | 42-0            |
|*kernel*       | 6.11.5-1        | 6.8.5-301       | 6.11.6-300      | 6.11.5-300      | 6.12.0-0.rc5.20241101git6c52d4da1c74.48 |
|*grub2-common* | 2.12-5          | 2.06-123        | 2.12-10         | 2.12-10         | 2.12-10         |
|*aardvark-dns* | 1.12.2-1        | 1.12.2-2        | 1.13.0-1        | 1.12.2-2        | 1.12.2-2        |
|*netavark*     | 1.12.1-3        | 1.12.2-1        | 1.13.0-1        | 1.12.2-1        | 1.12.2-1        |
|*buildah*      | 1.37.5+ds1-1    | 1.37.3-1        | 1.37.5-1        | 1.37.5-1        | 1.37.5-1        |
|*conmon*       | 2.1.12-3        | 2.1.12-2        | 2.1.12-3        | 2.1.12-3        | 2.1.12-3        |
|*container-selinux*| ?               | 2.233.0-1       | 2.233.0-1       | 2.233.0-1       | 2.233.0-1       |
|*containers-common*| ?               | 0.60.4-2        | 0.60.4-4        | 0.60.4-4        | 0.60.4-5        |
|*criu*         | 3.17.1-3        | 4.0-1           | 4.0-2           | 4.0-2           | 4.0-2           |
|*crun*         | 1.18.2-1        | 1.17-1          | 1.18.2-1        | 1.18.1-1        | 1.18.2-1        |
|*docker-ce*    | 5:27.3.1-1\~debian.12\~bookworm | ?               | ?               | ?               | ?               |
|*golang*       | 2:1.23\~2       | 1.22.7-1        | 1.23.2-2        | 1.23.2-2        | 1.23.2-2        |
|*gvisor-tap-vsock*| ?               | ?               | ?               | ?               | ?               |
|*nmap-ncat*    | 7.94+git20230807.3be01efb1+dfsg-4 | 7.92-2          | 7.92-3          | 7.92-3          | 7.92-3          |
|*passt*        | 2024-10-30      | 2024-09-06      | 2024-10-30      | 2024-10-30      | 2024-10-30      |
|*podman*       | 5.2.5-1         | 5.2.3-1         | 5.3.0\~rc2-1    | 5.2.5-1         | 5.3.0\~rc2-1    |
|*runc*         | 1.1.15+ds1-1    | 1.1.12-3        | 1.2.1-1         | 1.1.12-4        | 1.2.1-1         |
|*skopeo*       | 1.16.1+ds1-1+b1 | 1.16.1-1        | 1.16.1-1        | 1.16.1-1        | 1.16.1-2        |
|*slirp4netns*  | 1.2.1-1+b1      | 1.2.2-2         | 1.3.1-1         | 1.2.2-3         | 1.3.1-1         |
|*systemd*      | 256.7-3         | 255.13-1        | 256.7-1         | 256.7-1         | 256.7-1         |
|*tar*          | 1.34+dfsg-1.2+deb12u1 | 1.35-3          | 1.35-4          | 1.35-4          | 1.35-4          |

**Comment by edsantiago** [comment]
Broken 6.11.5 kernel; too-old crun and passt. I'm dropping this for today, we'll see what Wednesday brings.

**Comment by edsantiago** [comment]
Still the broken .5 kernel

- 20241106t123604z-f41f40d13
- 20241104t170243z-f41f40d13 &#x21D1; (built in #390)

|  |*debian*|*prior-fedora*|*fedora*|*fedora-aws*|*rawhide*|
|----|----|----|----|----|----|
|*kernel*       | 6.11.6-1        | 6.8.5-301       | 6.11.6-300      | 6.11.5-300      | 6.12.0-0.rc6.51 |
|               | 6.11.5-1&nbsp;&#x21D1; |                |                |                | 6.12.0-0.rc5.20241101git6c52d4da1c74.48&nbsp;&#x21D1; |
|*aardvark-dns* | 1.12.2-1        | 1.12.2-2        | 1.13.0-1        | 1.13.0-1        | 1.12.2-2        |
|               |                |                |                | 1.12.2-2&nbsp;&#x21D1; |                |
|*netavark*     | 1.12.1-3        | 1.12.2-1        | 1.13.0-1        | 1.13.0-1        | 1.12.2-1        |
|               |                |                |                | 1.12.2-1&nbsp;&#x21D1; |                |
|*criu*         | 3.19-2          | 4.0-1           | 4.0-2           | 4.0-2           | 4.0-2           |
|               | 3.17.1-3&nbsp;&#x21D1; |                |                |                |                |

**Comment by Luap99** [comment]
it is not yet in stable on f40 and f41 https://bodhi.fedoraproject.org/updates/FEDORA-2024-4c6f5993b8
https://bodhi.fedoraproject.org/updates/FEDORA-2024-8bcdafdfa2

Are we no installing from testing repo on aws? Or I think we noticed in the past that the aws images are a bit behind in package versions, maybe I should check the repo files there.

**Comment by edsantiago** [comment]
That's what I remember: aws has repos that don't match actual fedora. The only workaround I know for that is patience.

**Comment by Luap99** [comment]
One thing to note here is though we only run aws on current fedora right? We default to nftables as of 41 so we will not hit the bug there. Only the prior fedora (f40) will hit it but from your package versions `6.8.5-301` does not sound realistic there?!

**Comment by Luap99** [comment]
Well I guess we want aarch64 testing? In any case if we test f41 I don't think the kernel should cause issues for us as the default is nftables in netavark now. Only f40 will have this issue and we are not doing prior fedora on aws, are we?

**Comment by edsantiago** [comment]
Closing in favor of #392

**Pull request closed without merging**
