### PR TITLE
Add git-daemon packages to all distros

### PR DESCRIPTION
**Pull request by cevich**
Ref: https://github.com/containers/podman/issues/12851

### CODE REVIEW

**Comment by cevich** [comment]
@edsantiago assuming the build is successful (they were the other day), a bot will splat out the new image ID string for use downstream.

**Comment by cevich** [comment]
(in case you want to use it, either way I'll just merge this if it's okay)

**Comment by cevich** [comment]
@edsantiago I find [a `git-daemon-run` package](https://packages.ubuntu.com/impish/git-daemon-run) but nothing called `git daemon`.  Is that the same thing?

**Comment by cevich** [comment]
@edsantiago un-ping.  Found a page indicating `git-daemon-run` is the package name we want.

**Comment by edsantiago** [comment]
Sorry, I have no insight into Ubuntu package names. If `git-daemon-run` installs, and buildah tests run, then it's the right package. LGTM! And, thank you!

**Comment by edsantiago** [comment]
/lgtm
thanks!

**Review by edsantiago — APPROVED** [review]

**Comment by cevich** [comment]
Sure thing. Feel free to use that image ID if you need to re-enable the tests, otherwise it's np to just abandon it.

**Comment by edsantiago** [comment]
Yep, already in progress: https://github.com/containers/buildah/pull/3711

**Pull request merged**
