### PR TITLE
New VM build, just to see how things are

### PR DESCRIPTION
**Pull request by edsantiago**
New pasta (03-20). And whatever else comes in.

Also: install StrawberryPerl on Windows, see:

  https://github.com/containers/podman/pull/21991

First CI-detected problem:

    debian: The following packages have unmet dependencies:
    debian:  libfuse2t64 : Breaks: libfuse2 (< 2.9.9-8.1)

Solution attempted: remove libfuse2 from INSTALL_PACKAGES

Signed-off-by: Ed Santiago <santiago@redhat.com>

### CODE REVIEW

**Comment by edsantiago** [comment]
- 20240318t201745z-f39f38d13
- 20240227t125812z-f39f38d13 &#x21D1; (built in #331)

|  |*debian*|*prior-fedora*|*fedora*|*fedora-aws*|*rawhide*|
|----|----|----|----|----|----|
|*base*         | 13              | 38-1.6          | 39-1.5          | ?               | 41-0            |
|               |                |                |                |                |                |
|*kernel*       | 6.7.9-2         | 6.7.9-100       | 6.7.9-200       | 6.7.9-200       | 6.9.0-0.rc0.20240315gite5eb28f6d1af.7 |
|               | 6.6.15-2&nbsp;&#x21D1; | 6.7.5-100&nbsp;&#x21D1; | 6.7.6-200&nbsp;&#x21D1; | 6.7.5-200&nbsp;&#x21D1; | 6.8.0-0.rc6.49&nbsp;&#x21D1; |
|*aardvark-dns* | 1.4.0-5         | 1.10.0-1        | 1.10.0-1        | 1.10.0-1        | 1.10.0-1        |
|               |                |                |                |                |                |
|*netavark*     | 1.4.0-4         | 1.10.3-1        | 1.10.3-1        | 1.10.3-1        | 1.10.3-2        |
|               |                | 1.9.0-1&nbsp;&#x21D1; |                |                | 1.10.3-1&nbsp;&#x21D1; |
|*buildah*      | 1.33.5+ds1-4    | 1.34.0-1        | 1.35.0-1        | 1.35.0-1        | 1.35.0-1        |
|               |                |                | 1.34.1-1&nbsp;&#x21D1; | 1.34.0-1&nbsp;&#x21D1; | 1.34.0-4&nbsp;&#x21D1; |
|*conmon*       | 2.1.10+ds1-1+b1 | 2.1.10-1        | 2.1.10-1        | 2.1.10-1        | 2.1.10-1        |
|               | 2.1.10+ds1-1&nbsp;&#x21D1; | 2.1.8-2&nbsp;&#x21D1; |                |                | 2.1.8-4&nbsp;&#x21D1; |
|*container-selinux*| ?               | 2.228.1-1       | 2.230.0-1       | 2.230.0-1       | 2.230.0-1       |
|               |                |                | 2.229.0-1&nbsp;&#x21D1; | 2.229.0-1&nbsp;&#x21D1; | 2.229.0-2&nbsp;&#x21D1; |
|*containers-common*| ?               | 1-89            | 1-99            | 1-99            | 0.58.0-1        |
|               |                |                |                |                | 0.57.3-3&nbsp;&#x21D1; |
|*criu*         | 3.17.1-3        | 3.18-1          | 3.19-2          | 3.19-2          | 3.19-4          |
|               |                |                |                |                |                |
|*crun*         | 1.14.4-1        | 1.14.4-1        | 1.14.4-1        | 1.14.4-1        | 1.14.4-1        |
|               | 1.14.1-1&nbsp;&#x21D1; | 1.14.3-1&nbsp;&#x21D1; | 1.14.3-1&nbsp;&#x21D1; | 1.14.3-1&nbsp;&#x21D1; | 1.14.3-1&nbsp;&#x21D1; |
|*golang*       | 2:1.22~3        | 1.21.8-1        | 1.21.8-1        | 1.21.8-1        | 1.22.1-1        |
|               | 2:1.22~2&nbsp;&#x21D1; | 1.20.14-1&nbsp;&#x21D1; | 1.21.7-1&nbsp;&#x21D1; | 1.21.7-1&nbsp;&#x21D1; | 1.22.0-1&nbsp;&#x21D1; |
|*gvisor-tap-vsock*| ?               | 0.7.3-1         | 0.7.3-1         | 0.7.3-1         | 0.7.3-2         |
|               |                |                |                |                |                |
|*passt*        | 2024-02-20      | 2024-03-18      | 2024-03-18      | 2024-03-18      | 2024-03-18      |
|               |                | 2024-02-20&nbsp;&#x21D1; | 2024-02-20&nbsp;&#x21D1; | 2024-02-20&nbsp;&#x21D1; | 2024-02-20&nbsp;&#x21D1; |
|*podman*       | 4.9.3+ds1-1     | 4.9.3-2         | 4.9.3-1         | 4.9.3-1         | 5.0.0~rc6-2     |
|               |                |                |                |                | 5.0.0~rc1-3&nbsp;&#x21D1; |
|*runc*         | 1.1.12+ds1-2    | 1.1.12-1        | 1.1.12-1        | 1.1.12-1        | 1.1.12-3        |
|               | 1.1.12+ds1-1&nbsp;&#x21D1; |                |                |                |                |
|*skopeo*       | 1.13.3+ds1-2    | 1.14.2-1        | 1.15.0-1        | 1.14.2-1        | 1.14.2-2        |
|               |                |                | 1.14.2-1&nbsp;&#x21D1; |                |                |
|*slirp4netns*  | 1.2.1-1+b1      | 1.2.2-1         | 1.2.2-1         | 1.2.2-1         | 1.2.2-2         |
|               | 1.2.1-1&nbsp;&#x21D1; |                |                |                |                |
|*systemd*      | 255.4-1+b1      | 253.15-2        | 254.10-1        | 254.10-1        | 255.4-1         |
|               | 255.3-2&nbsp;&#x21D1; |                | 254.9-1&nbsp;&#x21D1; | 254.9-1&nbsp;&#x21D1; | 255.3-1&nbsp;&#x21D1; |
|*tar*          | 1.34+dfsg-1.2+deb12u1 | 1.34-8          | 1.35-2          | 1.35-2          | 1.35-3          |
|               |                |                |                |                |                |

**Comment by edsantiago** [comment]
Converted to draft, because pasta

**Comment by edsantiago** [comment]
- 20240319t134325z-f39f38d13
- 20240227t125812z-f39f38d13 &#x21D1; (built in #331)

|  |*debian*|*prior-fedora*|*fedora*|*fedora-aws*|*rawhide*|
|----|----|----|----|----|----|
|*base*         | 13              | 38-1.6          | 39-1.5          | ?               | 41-0            |
|               |                |                |                |                |                |
|*kernel*       | 6.7.9-2         | 6.7.9-100       | 6.7.10-200      | 6.7.9-200       | 6.9.0-0.rc0.20240315gite5eb28f6d1af.7 |
|               | 6.6.15-2&nbsp;&#x21D1; | 6.7.5-100&nbsp;&#x21D1; | 6.7.6-200&nbsp;&#x21D1; | 6.7.5-200&nbsp;&#x21D1; | 6.8.0-0.rc6.49&nbsp;&#x21D1; |
|*aardvark-dns* | 1.4.0-5         | 1.10.0-1        | 1.10.0-1        | 1.10.0-1        | 1.10.0-1        |
|               |                |                |                |                |                |
|*netavark*     | 1.4.0-4         | 1.10.3-1        | 1.10.3-1        | 1.10.3-1        | 1.10.3-2        |
|               |                | 1.9.0-1&nbsp;&#x21D1; |                |                | 1.10.3-1&nbsp;&#x21D1; |
|*buildah*      | 1.33.5+ds1-4    | 1.34.0-1        | 1.35.0-1        | 1.35.0-1        | 1.35.0-1        |
|               |                |                | 1.34.1-1&nbsp;&#x21D1; | 1.34.0-1&nbsp;&#x21D1; | 1.34.0-4&nbsp;&#x21D1; |
|*conmon*       | 2.1.10+ds1-1+b1 | 2.1.10-1        | 2.1.10-1        | 2.1.10-1        | 2.1.10-1        |
|               | 2.1.10+ds1-1&nbsp;&#x21D1; | 2.1.8-2&nbsp;&#x21D1; |                |                | 2.1.8-4&nbsp;&#x21D1; |
|*container-selinux*| ?               | 2.228.1-1       | 2.230.0-1       | 2.230.0-1       | 2.230.0-1       |
|               |                |                | 2.229.0-1&nbsp;&#x21D1; | 2.229.0-1&nbsp;&#x21D1; | 2.229.0-2&nbsp;&#x21D1; |
|*containers-common*| ?               | 1-89            | 1-99            | 1-99            | 0.58.0-1        |
|               |                |                |                |                | 0.57.3-3&nbsp;&#x21D1; |
|*criu*         | 3.17.1-3        | 3.18-1          | 3.19-2          | 3.19-2          | 3.19-4          |
|               |                |                |                |                |                |
|*crun*         | 1.14.4-1        | 1.14.4-1        | 1.14.4-1        | 1.14.4-1        | 1.14.4-1        |
|               | 1.14.1-1&nbsp;&#x21D1; | 1.14.3-1&nbsp;&#x21D1; | 1.14.3-1&nbsp;&#x21D1; | 1.14.3-1&nbsp;&#x21D1; | 1.14.3-1&nbsp;&#x21D1; |
|*golang*       | 2:1.22~3        | 1.21.8-1        | 1.21.8-1        | 1.21.8-1        | 1.22.1-1        |
|               | 2:1.22~2&nbsp;&#x21D1; | 1.20.14-1&nbsp;&#x21D1; | 1.21.7-1&nbsp;&#x21D1; | 1.21.7-1&nbsp;&#x21D1; | 1.22.0-1&nbsp;&#x21D1; |
|*gvisor-tap-vsock*| ?               | 0.7.3-1         | 0.7.3-1         | 0.7.3-1         | 0.7.3-2         |
|               |                |                |                |                |                |
|*passt*        | 2024-02-20      | 2024-03-19      | 2024-03-19      | 2024-03-19      | 2024-03-19      |
|               |                | 2024-02-20&nbsp;&#x21D1; | 2024-02-20&nbsp;&#x21D1; | 2024-02-20&nbsp;&#x21D1; | 2024-02-20&nbsp;&#x21D1; |
|*podman*       | 4.9.3+ds1-1     | 4.9.3-2         | 4.9.3-1         | 4.9.3-1         | 5.0.0~rc6-2     |
|               |                |                |                |                | 5.0.0~rc1-3&nbsp;&#x21D1; |
|*runc*         | 1.1.12+ds1-2    | 1.1.12-1        | 1.1.12-1        | 1.1.12-1        | 1.1.12-3        |
|               | 1.1.12+ds1-1&nbsp;&#x21D1; |                |                |                |                |
|*skopeo*       | 1.13.3+ds1-2    | 1.14.2-1        | 1.15.0-1        | 1.14.2-1        | 1.14.2-2        |
|               |                |                | 1.14.2-1&nbsp;&#x21D1; |                |                |
|*slirp4netns*  | 1.2.1-1+b1      | 1.2.2-1         | 1.2.2-1         | 1.2.2-1         | 1.2.2-2         |
|               | 1.2.1-1&nbsp;&#x21D1; |                |                |                |                |
|*systemd*      | 255.4-1+b1      | 253.15-2        | 254.10-1        | 254.10-1        | 255.4-1         |
|               | 255.3-2&nbsp;&#x21D1; |                | 254.9-1&nbsp;&#x21D1; | 254.9-1&nbsp;&#x21D1; | 255.3-1&nbsp;&#x21D1; |
|*tar*          | 1.34+dfsg-1.2+deb12u1 | 1.34-8          | 1.35-2          | 1.35-2          | 1.35-3          |
|               |                |                |                |                |                |

**Comment by edsantiago** [comment]
- 20240320t134523z-f39f38d13
- 20240222t143004z-f39f38d13 &#x21D1; (built in #329)

|  |*debian*|*prior-fedora*|*fedora*|*fedora-aws*|*rawhide*|
|----|----|----|----|----|----|
|*base*         | 13              | 38-1.6          | 39-1.5          | ?               | 41-0            |
|               |                |                |                |                |                |
|*kernel*       | 6.7.9-2         | 6.7.9-100       | 6.7.10-200      | 6.7.9-200       | 6.9.0-0.rc0.20240319gitb3603fcb79b1.11 |
|               | 6.6.15-2&nbsp;&#x21D1; | 6.7.5-100&nbsp;&#x21D1; | 6.7.5-200&nbsp;&#x21D1; | 6.7.5-200&nbsp;&#x21D1; | 6.8.0-0.rc5.41&nbsp;&#x21D1; |
|*aardvark-dns* | 1.4.0-5         | 1.10.0-1        | 1.10.0-1        | 1.10.0-1        | 1.10.0-1        |
|               |                |                |                |                |                |
|*netavark*     | 1.4.0-4         | 1.10.3-1        | 1.10.3-1        | 1.10.3-1        | 1.10.3-2        |
|               |                | 1.9.0-1&nbsp;&#x21D1; |                |                | 1.10.3-1&nbsp;&#x21D1; |
|*buildah*      | 1.33.5+ds1-4    | 1.34.0-1        | 1.35.1-1        | 1.35.0-1        | 1.35.0-1        |
|               |                |                | 1.34.0-1&nbsp;&#x21D1; | 1.34.0-1&nbsp;&#x21D1; | 1.34.0-4&nbsp;&#x21D1; |
|*conmon*       | 2.1.10+ds1-1+b1 | 2.1.10-1        | 2.1.10-1        | 2.1.10-1        | 2.1.10-1        |
|               | 2.1.10+ds1-1&nbsp;&#x21D1; | 2.1.8-2&nbsp;&#x21D1; |                |                | 2.1.8-4&nbsp;&#x21D1; |
|*container-selinux*| ?               | 2.228.1-1       | 2.230.0-1       | 2.230.0-1       | 2.230.0-1       |
|               |                |                | 2.229.0-1&nbsp;&#x21D1; | 2.229.0-1&nbsp;&#x21D1; | 2.229.0-2&nbsp;&#x21D1; |
|*containers-common*| ?               | 1-89            | 1-99            | 1-99            | 0.58.0-3        |
|               |                |                |                |                | 0.57.3-3&nbsp;&#x21D1; |
|*criu*         | 3.17.1-3        | 3.18-1          | 3.19-2          | 3.19-2          | 3.19-4          |
|               |                |                |                |                |                |
|*crun*         | 1.14.4-1        | 1.14.4-1        | 1.14.4-1        | 1.14.4-1        | 1.14.4-1        |
|               | 1.14.1-1&nbsp;&#x21D1; | 1.14.3-1&nbsp;&#x21D1; | 1.14.3-1&nbsp;&#x21D1; | 1.14.3-1&nbsp;&#x21D1; | 1.14.3-1&nbsp;&#x21D1; |
|*golang*       | 2:1.22~3        | 1.21.8-1        | 1.21.8-1        | 1.21.8-1        | 1.22.1-1        |
|               | 2:1.21~3&nbsp;&#x21D1; | 1.20.14-1&nbsp;&#x21D1; | 1.21.7-1&nbsp;&#x21D1; | 1.21.7-1&nbsp;&#x21D1; | 1.22.0-1&nbsp;&#x21D1; |
|*gvisor-tap-vsock*| ?               | 0.7.3-1         | 0.7.3-1         | 0.7.3-1         | 0.7.3-2         |
|               |                |                |                |                |                |
|*passt*        | 2024-02-20      | 2024-03-19      | 2024-03-19      | 2024-03-19      | 2024-03-20      |
|               |                | 2024-02-20&nbsp;&#x21D1; | 2024-02-20&nbsp;&#x21D1; | 2024-02-20&nbsp;&#x21D1; | 2024-02-20&nbsp;&#x21D1; |
|*podman*       | 4.9.3+ds1-1     | 4.9.3-2         | 4.9.3-1         | 4.9.3-1         | 5.0.0~rc6-2     |
|               |                | 4.8.3-1&nbsp;&#x21D1; |                | 4.9.0-1&nbsp;&#x21D1; | 5.0.0~rc1-3&nbsp;&#x21D1; |
|*runc*         | 1.1.12+ds1-2    | 1.1.12-1        | 1.1.12-1        | 1.1.12-1        | 1.1.12-3        |
|               | 1.1.12+ds1-1&nbsp;&#x21D1; |                |                |                |                |
|*skopeo*       | 1.13.3+ds1-2    | 1.14.2-1        | 1.15.0-1        | 1.14.2-1        | 1.14.2-2        |
|               |                | 1.14.1-1&nbsp;&#x21D1; | 1.14.2-1&nbsp;&#x21D1; |                |                |
|*slirp4netns*  | 1.2.1-1+b1      | 1.2.2-1         | 1.2.2-1         | 1.2.2-1         | 1.2.2-2         |
|               | 1.2.1-1&nbsp;&#x21D1; |                |                |                |                |
|*systemd*      | 255.4-1+b1      | 253.15-2        | 254.10-1        | 254.10-1        | 255.4-1         |
|               | 255.3-2&nbsp;&#x21D1; |                | 254.9-1&nbsp;&#x21D1; | 254.9-1&nbsp;&#x21D1; | 255.3-1&nbsp;&#x21D1; |
|*tar*          | 1.34+dfsg-1.2+deb12u1 | 1.34-8          | 1.35-2          | 1.35-2          | 1.35-3          |
|               |                |                |                |                |                |

**Comment by edsantiago** [comment]
Pasta 03-20 on all Fedoras. Kernel 6.9.0 rc0 on rawhide. Podman test PR is [22082](https://github.com/containers/podman/pull/22082); I've also been testing all the above iterations in 17831. @cevich @Luap99 PTAL; barring any last-minute pasta emergencies, this is ready to go.

- 20240320t153921z-f39f38d13
- 20240222t143004z-f39f38d13 &#x21D1; (built in #329)

|  |*debian*|*prior-fedora*|*fedora*|*fedora-aws*|*rawhide*|
|----|----|----|----|----|----|
|*base*         | 13              | 38-1.6          | 39-1.5          | ?               | 41-0            |
|               |                |                |                |                |                |
|*kernel*       | 6.7.9-2         | 6.7.9-100       | 6.7.10-200      | 6.7.9-200       | 6.9.0-0.rc0.20240318gitf6cef5f8c37f.10 |
|               | 6.6.15-2&nbsp;&#x21D1; | 6.7.5-100&nbsp;&#x21D1; | 6.7.5-200&nbsp;&#x21D1; | 6.7.5-200&nbsp;&#x21D1; | 6.8.0-0.rc5.41&nbsp;&#x21D1; |
|*aardvark-dns* | 1.4.0-5         | 1.10.0-1        | 1.10.0-1        | 1.10.0-1        | 1.10.0-1        |
|               |                |                |                |                |                |
|*netavark*     | 1.4.0-4         | 1.10.3-1        | 1.10.3-1        | 1.10.3-1        | 1.10.3-2        |
|               |                | 1.9.0-1&nbsp;&#x21D1; |                |                | 1.10.3-1&nbsp;&#x21D1; |
|*buildah*      | 1.33.5+ds1-4    | 1.34.0-1        | 1.35.1-1        | 1.35.0-1        | 1.35.0-1        |
|               |                |                | 1.34.0-1&nbsp;&#x21D1; | 1.34.0-1&nbsp;&#x21D1; | 1.34.0-4&nbsp;&#x21D1; |
|*conmon*       | 2.1.10+ds1-1+b1 | 2.1.10-1        | 2.1.10-1        | 2.1.10-1        | 2.1.10-1        |
|               | 2.1.10+ds1-1&nbsp;&#x21D1; | 2.1.8-2&nbsp;&#x21D1; |                |                | 2.1.8-4&nbsp;&#x21D1; |
|*container-selinux*| ?               | 2.228.1-1       | 2.230.0-1       | 2.230.0-1       | 2.230.0-1       |
|               |                |                | 2.229.0-1&nbsp;&#x21D1; | 2.229.0-1&nbsp;&#x21D1; | 2.229.0-2&nbsp;&#x21D1; |
|*containers-common*| ?               | 1-89            | 1-99            | 1-99            | 0.58.0-1        |
|               |                |                |                |                | 0.57.3-3&nbsp;&#x21D1; |
|*criu*         | 3.17.1-3        | 3.18-1          | 3.19-2          | 3.19-2          | 3.19-4          |
|               |                |                |                |                |                |
|*crun*         | 1.14.4-1        | 1.14.4-1        | 1.14.4-1        | 1.14.4-1        | 1.14.4-1        |
|               | 1.14.1-1&nbsp;&#x21D1; | 1.14.3-1&nbsp;&#x21D1; | 1.14.3-1&nbsp;&#x21D1; | 1.14.3-1&nbsp;&#x21D1; | 1.14.3-1&nbsp;&#x21D1; |
|*golang*       | 2:1.22~3        | 1.21.8-1        | 1.21.8-1        | 1.21.8-1        | 1.22.1-1        |
|               | 2:1.21~3&nbsp;&#x21D1; | 1.20.14-1&nbsp;&#x21D1; | 1.21.7-1&nbsp;&#x21D1; | 1.21.7-1&nbsp;&#x21D1; | 1.22.0-1&nbsp;&#x21D1; |
|*gvisor-tap-vsock*| ?               | 0.7.3-1         | 0.7.3-1         | 0.7.3-1         | 0.7.3-2         |
|               |                |                |                |                |                |
|*passt*        | 2024-02-20      | 2024-03-20      | 2024-03-20      | 2024-03-20      | 2024-03-20      |
|               |                | 2024-02-20&nbsp;&#x21D1; | 2024-02-20&nbsp;&#x21D1; | 2024-02-20&nbsp;&#x21D1; | 2024-02-20&nbsp;&#x21D1; |
|*podman*       | 4.9.3+ds1-1     | 4.9.3-2         | 4.9.3-1         | 4.9.3-1         | 5.0.0~rc6-2     |
|               |                | 4.8.3-1&nbsp;&#x21D1; |                | 4.9.0-1&nbsp;&#x21D1; | 5.0.0~rc1-3&nbsp;&#x21D1; |
|*runc*         | 1.1.12+ds1-2    | 1.1.12-1        | 1.1.12-1        | 1.1.12-1        | 1.1.12-3        |
|               | 1.1.12+ds1-1&nbsp;&#x21D1; |                |                |                |                |
|*skopeo*       | 1.13.3+ds1-2    | 1.14.2-1        | 1.15.0-1        | 1.14.2-1        | 1.14.2-2        |
|               |                | 1.14.1-1&nbsp;&#x21D1; | 1.14.2-1&nbsp;&#x21D1; |                |                |
|*slirp4netns*  | 1.2.1-1+b1      | 1.2.2-1         | 1.2.2-1         | 1.2.2-1         | 1.2.2-2         |
|               | 1.2.1-1&nbsp;&#x21D1; |                |                |                |                |
|*systemd*      | 255.4-1+b1      | 253.15-2        | 254.10-1        | 254.10-1        | 255.4-1         |
|               | 255.3-2&nbsp;&#x21D1; |                | 254.9-1&nbsp;&#x21D1; | 254.9-1&nbsp;&#x21D1; | 255.3-1&nbsp;&#x21D1; |
|*tar*          | 1.34+dfsg-1.2+deb12u1 | 1.34-8          | 1.35-2          | 1.35-2          | 1.35-3          |
|               |                |                |                |                |                |

**Review by cevich — APPROVED** [review]
LGTM.  Thanks Ed for driving these builds, you're much faster at it than I am.

**Comment by cevich** [comment]
Oh, I'm assuming this version should **NOT** be tagged due to the pasta thing?

**Comment by edsantiago** [comment]
I think it'd be fine to tag this, but let's hold off and see (1) how it fares in Podman-land, and then (2) how #338 fares, because we might as well 2birds1stone

**Comment by cevich** [comment]
SGTM.  Would you mind doing the tagging then? You seem to be much more on top of the situation than I.

**Comment by edsantiago** [comment]
Gladly. I'll take care of it, and also the buildah futzing that'll have to be done now that we have crun > 1.14.1 (some skipped tests will need to be reenabled)

**Comment by cevich** [comment]
Thanks Ed, I appreciate it.

**Pull request merged**
