### PR TITLE
Update automation-library

### PR DESCRIPTION
**Pull request by cevich**
Significantly, this version defines a `passthrough_envars()` function to
replace the two duplicate definitions in podman and buildah CI.  When
incorporating the new images into those environments, the duplicates
should be removed.

Also included is an important updates to the build-push script that
improves debugging in cases where the `--nopush` argument is used.

### CODE REVIEW

**Comment by cevich** [comment]
***note to me***: The main.sh script should probably be updated to fetch/install the latest c/automation build-push at runtime to make it easier to maintain/fix problems w/o rebuilding CI VM images.

**Comment by cevich** [comment]
Ugh, Debian SID kernel's broken.  Will try again later.

**Comment by cevich** [comment]
Ugh, [the debian SID build](https://cirrus-ci.com/task/6067890294620160?logs=main#L801) appears to be [hitting something similar to an upstream bug report](https://www.mail-archive.com/debian-bugs-dist@lists.debian.org/msg1929869.html).

@lsm5 or @edsantiago (or anyone!) when you have a moment, maybe you've dealt with Debian kernel updates before.  [The update-to-sid command](https://github.com/cevich/automation_images/blob/9c001f30c0ad9ed02120961d3934533965828e09/base_images/debian_base-setup.sh#L41C33-L41C33) has been failing for a few weeks (or more).  I wouldn't be surprised if google's messed with/customized the kernel/toolchain/scripts in some way - the starting VM image is provided by google and intended exclusively for GCP-use.  Can you think of a way to work around this?

Honestly I don't really care about the latest/greatest SID kernel...however I'll bet that if we don't install it, [all the ZFS-support crap](https://github.com/cevich/automation_images/blob/9c001f30c0ad9ed02120961d3934533965828e09/cache_images/debian_packaging.sh#L123-L130) needed by c/storage CI will subsequently break :cry:

**Comment by edsantiago** [comment]
Can you carry and applyt [this patch](https://git.savannah.gnu.org/cgit/grub.git/commit/?id=99e05ab555f013b5ce45a3fd04f8ccd5f4e5bf95)?

**Comment by cevich** [comment]
Oh wow, thanks for tracking that down @edsantiago.  I'll give it a whirl.

**Comment by cevich** [comment]
Darn.  Okay I'll try using that template patch to make a patch of my own...

**Comment by edsantiago** [comment]
Have you tried a simple `grub-mkconfig` to just reset /boot/grub?

**Comment by cevich** [comment]
> Have you tried a simple grub-mkconfig to just reset /boot/grub?

Sorry I don't follow.  Isn't the issue with some scripts that are incompatible in the new kernel vs old `grub-common`?  What am I missing?

**Comment by cevich** [comment]
Also I don't really know/remember how this stuff works.  I see two copies copy of `grub.cfg`, one under `/boot/grub/` and another under `/boot/efi/EFI/debian/`.

---

I'm still wondering if an upgrade of just `grub-common` (separate from kernel) might work.  So far it seems to make a difference on a test VM.  I'm going to give that another try for now...

**Comment by cevich** [comment]
...follow up on the patch idea:  I tried manually updating the scripts, but there are changes in `/etc/grub.d/10-linux` that I can't reconcile with the `util/grub.d/10_linux.in` in the patch.  I tried, but the script is too big and complex for me to grok.

**Comment by cevich** [comment]
...and of course! :angry: my local test VM puked on updating ZFS, so we probably get to look forward to that :cursing_face: next :sweat: 

Some crap about DKMS and kernel headers, I don't remember.  Rage-deleted the VM :rofl:

**Comment by cevich** [comment]
:partying_face: that pre-update of `grub-common` [seems to have worked](https://cirrus-ci.com/task/6014783158222848) (or I got lucky and SID fixed whatever needed fixing).  Hopefully the ZFS install will behave...

**Comment by cevich** [comment]
Force-push: Hitting 45m timeout on debian cache-image build.  Bumped it to 60m.

**Comment by cevich** [comment]
Yep, as predicted the debian cache image build is dying on ZFS crap.

```
    debian: Failed to process /etc/kernel/header_postinst.d at /var/lib/dpkg/info/linux-headers-6.5.0-1-cloud-amd64.postinst line 11.
    debian: dpkg: error processing package linux-headers-6.5.0-1-cloud-amd64 (--configure):
    debian:  installed linux-headers-6.5.0-1-cloud-amd64 package post-installation script subprocess returned error exit status 1
    debian: dpkg: dependency problems prevent configuration of linux-headers-cloud-amd64:
    debian:  linux-headers-cloud-amd64 depends on linux-headers-6.5.0-1-cloud-amd64 (= 6.5.3-1); however:
    debian:   Package linux-headers-6.5.0-1-cloud-amd64 is not configured yet.
    debian:
    debian: dpkg: error processing package linux-headers-cloud-amd64 (--configure):
    debian:  dependency problems - leaving unconfigured
    debian: dpkg: dependency problems prevent configuration of linux-headers-amd64:
    debian:  linux-headers-amd64 depends on linux-headers-6.5.0-1-amd64 (= 6.5.3-1); however:
    debian:   Package linux-headers-6.5.0-1-amd64 is not configured yet.
    debian:
    debian: dpkg: error processing package linux-headers-amd64 (--configure):
    debian:  dependency problems - leaving unconfigured
    debian: dpkg: dependency problems prevent configuration of zfs-zed:
    debian:  zfs-zed depends on zfs-modules | zfs-dkms; however:
    debian:   Package zfs-modules is not installed.
    debian:   Package zfs-dkms which provides zfs-modules is not configured yet.
    debian:   Package zfs-dkms is not configured yet.
    debian:
    debian: dpkg: error processing package zfs-zed (--configure):
    debian:  dependency problems - leaving unconfigured
```

I can't fix this and it's been a constant PITA to support for CI in a single REPO (c/storage).  I'm going to strip it out and deal with CI there later - hopefully we can just drop ZFS CI support entirely.  It doesn't pay any of our bills.

**Comment by cevich** [comment]
Oh goodie!

**Pull request merged**
