### PR TITLE
Add wireguard-tools and passt packages

### PR DESCRIPTION
**Pull request by cevich**
Fixes: #234
Fixes: #232

### CODE REVIEW

**Comment by cevich** [comment]
There ya go @Luap99, just blast that `c5518085466095616` image-suffix value into whatever repo's CI needs the new pacakges (remember to update the Distro names to F37 & F36 too).

**Comment by cevich** [comment]
> can we use the copr https://copr.fedorainfracloud.org/coprs/sbrivio/passt/ instead?

Sure, no problem.

**Comment by Luap99** [comment]
@cevich updates-testing from the main repos should also work

**Comment by Luap99** [comment]
CI is red. Given https://bodhi.fedoraproject.org/updates/FEDORA-2022-754a5818f2, we could also wait a couple of days until this lands in stable.

**Comment by cevich** [comment]
Let's try just enabling it for the latest podman CI VMs...

**Comment by cevich** [comment]
Context: CI was red simply because the `copr` command doesn't exist by default in the F36 image.  The F37 image is already setup to use updates-testing, however using copr for new feature testing (assuming this is) might be more flexible.  Let's see if just having this in F37 can work...

**Comment by Luap99** [comment]
SGTM

**Comment by cevich** [comment]
Once again for the third time.

**Comment by cevich** [comment]
E-mailed cirrus-support.  There's a bug (likely on the github-side) causing a failure-to-clone.

**Comment by cevich** [comment]
@Luap99 there we go, got the build to pass.  Please use the image suffix referenced above.

**Comment by Luap99** [comment]
> @Luap99 there we go, got the build to pass. Please use the image suffix referenced above.

Yeah thanks, already pushed in https://github.com/containers/podman/pull/16525

**Comment by cevich** [comment]
K, good deal.  I'm going to merge this then.  But if any more image changes/updates are needed I've got another PR coming to this repo. shortly (to use the release-F37 cloud-images instead of devel).

**Pull request merged**
