### PR TITLE
[CI:TOOLING] Fix silent imgobsolete error + check status JSON

### PR DESCRIPTION
**Pull request by cevich**
Fixes: #186 ([Example log](https://cirrus-ci.com/task/5398202080821248))

For whatever reason, the `aws` CLI does not exit non-zero if there was
an error obsoleting an image.  Worse, it forces callers to verify a JSON
blob as well.

Fix this, and improve the script by accumulating any errors and exiting
non-zero after the entire loop finishes.  In the case of `aws`,
additionally verify the output JSON provides positive confirmation of a
successful update.

Signed-off-by: Chris Evich <cevich@redhat.com>

### CODE REVIEW

**Comment by cevich** [comment]
@edsantiago PTAL when you get a chance, should be an easy one.

Meanwhile, I've got to actually try and figure out why _some_ EC2 images are throwing a permission error when this script runs...

**Comment by edsantiago** [comment]
How did you test this? Did you? I've never used `let`, and it turns out there's an excellent reason for that. See `bash(1)`, or try this, to find out why:
```bash
$ ERRORS=0
$ let "ERRORS++"
```
(This assumes you have a color-changing prompt that will immediately let you know what happens).

**Comment by cevich** [comment]
> How did you test this? Did you?

Actually I did and believed it worked, but apparently I wasn't paying enough attention or something...

**Comment by cevich** [comment]
...huh, yeah it seems to work fine for me:

```bash
~/dev/automation_images (import_images|✔) $ bash
[cevich@fedora automation_images]$ F=0
[cevich@fedora automation_images]$ let "F++"
[cevich@fedora automation_images]$ echo $F
1
[cevich@fedora automation_images]$ let "F++"
[cevich@fedora automation_images]$ echo $?
0
[cevich@fedora automation_images]$ echo $F
2
```

Is this the behavior you're concerned about: `If the last arg evaluates to 0, let returns  1;  0 is returned otherwise.`?  ERRORS is incrementing, and unless it wraps at some big number should never be 0...oh wait, I see.  The first one does return 1 doesn't it.  Ugh.  Okay I'll fix it.

**Comment by cevich** [comment]
Okay it's fixed.  What odd behavior, I've used `let` for ages and never noticed that return's 1 thing.  I wonder what the intent behind that design was, seems to make the call less generally-useful :disappointed:

**Comment by edsantiago** [comment]
LGTM

**Comment by cevich** [comment]
Thanks @edsantiago I appreciate it.

**Pull request merged**
