### PR TITLE
Debian: remove force-cgroups-v1 code

### PR DESCRIPTION
**Pull request by edsantiago**
Per discussion in 2024-03-20 Planning meeting, we will no
longer be testing runc in CI. And cgroups V1 is dead too.
    
Signed-off-by: Ed Santiago <santiago@redhat.com>

### CODE REVIEW

**Comment by edsantiago** [comment]
[Packages are identical to #338]

**Comment by edsantiago** [comment]
Well, [this is not going to be easy](https://cirrus-ci.com/build/5282798100021248).

**Comment by edsantiago** [comment]
- 20240514t134014z-f40f39d13
- 20240513t140131z-f40f39d13 &#x21D1; (built in #351)

|  |*debian*|*prior-fedora*|*fedora*|*fedora-aws*|*rawhide*|
|----|----|----|----|----|----|
|*kernel*       | 6.7.12-1        | 6.8.9-200       | 6.8.9-300       | 6.8.9-300       | 6.9.0-64        |
|               |                |                |                |                | 6.9.0-0.rc7.20240510git448b3fe5a0ea.62&nbsp;&#x21D1; |
|*container-selinux*| ?               | 2.231.0-1       | 2.231.0-1       | 2.230.0-1       | 2.231.0-1       |
|               |                | 2.230.0-1&nbsp;&#x21D1; |                |                |                |
|*passt*        | 2024-04-26      | 2024-04-26      | 2024-05-10      | 2024-05-10      | 2024-05-10      |
|               |                |                |                | 2024-04-26&nbsp;&#x21D1; |                |
|*podman*       | 4.9.4+ds1-1     | 4.9.4-1         | 5.0.3-1         | 5.0.2-1         | 5.0.3-1         |
|               |                |                |                |                | 5.0.2-1&nbsp;&#x21D1; |
|*systemd*      | 255.5-1         | 254.10-1        | 255.6-1         | 255.6-1         | 256~rc1^20240509git1781de1-2 |
|               |                |                |                |                | 255.5-1&nbsp;&#x21D1; |

**Comment by Luap99** [comment]
Think of the all the v1/v2 conditionals that we can remove in the tests and eventually the code as well

**Comment by edsantiago** [comment]
- 20240528t194313z-f40f39d13
- 20240513t140131z-f40f39d13 &#x21D1; (built in #351)

|  |*debian*|*prior-fedora*|*fedora*|*fedora-aws*|*rawhide*|
|----|----|----|----|----|----|
|*kernel*       | 6.8.11-1        | 6.8.10-200      | 6.8.5-301       | 6.8.5-301       | 6.9.0-64        |
|               | 6.7.12-1&nbsp;&#x21D1; | 6.8.9-200&nbsp;&#x21D1; | 6.8.9-300&nbsp;&#x21D1; | 6.8.9-300&nbsp;&#x21D1; | 6.9.0-0.rc7.20240510git448b3fe5a0ea.62&nbsp;&#x21D1; |
|*buildah*      | 1.33.7+ds1-1    | 1.35.4-1        | 1.36.0-1        | 1.35.4-1        | 1.35.4-1        |
|               |                | 1.35.3-1&nbsp;&#x21D1; | 1.35.4-1&nbsp;&#x21D1; | 1.35.3-1&nbsp;&#x21D1; |                |
|*conmon*       | 2.1.10+ds1-1+b1 | 2.1.10-1        | 2.1.12-1        | 2.1.10-1        | 2.1.10-1        |
|               |                |                | 2.1.10-1&nbsp;&#x21D1; |                |                |
|*container-selinux*| ?               | 2.231.0-1       | 2.231.0-1       | 2.231.0-1       | 2.231.0-6       |
|               |                | 2.230.0-1&nbsp;&#x21D1; |                | 2.230.0-1&nbsp;&#x21D1; | 2.231.0-1&nbsp;&#x21D1; |
|*containers-common*| ?               | 1-99            | 0.59.0-1        | 0.58.0-2        | 0.59.0-1        |
|               |                |                | 0.58.0-2&nbsp;&#x21D1; |                | 0.58.0-18&nbsp;&#x21D1; |
|*crun*         | 1.15-1          | 1.15-1          | 1.15-1          | 1.15-1          | 1.15-1          |
|               |                | 1.14.4-1&nbsp;&#x21D1; |                | 1.14.4-1&nbsp;&#x21D1; |                |
|*docker-ce*    | 5:26.1.3-1~debian.12~bookworm | ?               | ?               | ?               | ?               |
|               | 5:26.1.2-1~debian.12~bookworm&nbsp;&#x21D1; |                |                |                |                |
|*golang*       | 2:1.22~3        | 1.21.10-1       | 1.22.3-1        | 1.22.3-1        | 1.22.3-1        |
|               |                | 1.21.9-1&nbsp;&#x21D1; |                | 1.22.2-1&nbsp;&#x21D1; |                |
|*passt*        | 2024-04-26      | 2024-05-10      | 2024-05-10      | 2024-05-10      | 2024-05-23      |
|               |                | 2024-04-26&nbsp;&#x21D1; |                | 2024-04-26&nbsp;&#x21D1; | 2024-05-10&nbsp;&#x21D1; |
|*podman*       | 4.9.4+ds1-1     | 4.9.4-1         | 5.1.0~rc1-1     | 5.0.3-1         | 5.0.3-1         |
|               |                |                | 5.0.3-1&nbsp;&#x21D1; | 5.0.2-1&nbsp;&#x21D1; | 5.0.2-1&nbsp;&#x21D1; |
|*skopeo*       | 1.13.3+ds1-2+b1 | 1.15.0-1        | 1.15.1-1        | 1.15.0-1        | 1.15.1-1        |
|               |                |                | 1.15.0-1&nbsp;&#x21D1; |                | 1.15.0-1&nbsp;&#x21D1; |
|*systemd*      | 256~rc3-4       | 254.12-1        | 255.7-1         | 255.6-1         | 256~rc3-1       |
|               | 255.5-1&nbsp;&#x21D1; | 254.10-1&nbsp;&#x21D1; | 255.6-1&nbsp;&#x21D1; |                | 255.5-1&nbsp;&#x21D1; |

**Comment by edsantiago** [comment]
sigh.....

**Review by cevich — APPROVED** [review]
Thanks for taking care of this Ed.

**Comment by edsantiago** [comment]
- 20240529t141726z-f40f39d13
- 20240528t194313z-f40f39d13 &#x21D1; (built in #338)

|  |*debian*|*prior-fedora*|*fedora*|*fedora-aws*|*rawhide*|
|----|----|----|----|----|----|
|*systemd*      | 256~rc3-5       | 254.12-1        | 255.7-1         | 255.7-1         | 256~rc3-1       |
|               | 256~rc3-4&nbsp;&#x21D1; |                |                | 255.6-1&nbsp;&#x21D1; |                |

**Comment by edsantiago** [comment]
CI is passing in [podman](https://github.com/containers/podman/pull/22838), [buildah](https://github.com/containers/buildah/pull/5550), and [skopeo](https://github.com/containers/skopeo/pull/2342).

**Comment by edsantiago** [comment]
@cevich if you have a moment could you please give a final once-over and then merge? My change is in e50990987fc51564c93bb4442c958195d14922a0, all other commits are @mtrmac's from #355. I would like to tag this once it merges. TIA.

**Review by cevich — APPROVED** [review]
LGTM, thanks for seeing this through.  In my mind at least, there's a bunch of comments and code in podman CI that (when using these images) will confusingly suggest CGv1 is in use.  Are there any "cgroupsv1" cleanup/followup issues or cards that need creating?

**Comment by edsantiago** [comment]
Thank you. Yes, there will be a ton of cleanup needed to remove special-case conditionals. I've chosen not to tackle that yet.

**Comment by cevich** [comment]
> I've chosen not to tackle that yet.

That's fine, I or someone else may be able to help with this.  I just wanted to know if you had already opened an issue/card or set a personal reminder.  I'll go ahead and file a Jira card.

**Pull request merged**
