### PR TITLE
Use updates-testing for podman-py image

### PR DESCRIPTION
**Pull request by cevich**
Ref: https://github.com/containers/podman-py/pull/235

### CODE REVIEW

**Comment by lsm5** [comment]
@umohnani8 we might need the image id from here in a podman-py PR, might wanna include it in the lint PR itself.

**Comment by cevich** [comment]
Assuming the build works, it's going to be `c20230207t150657z-f37f36u2204`.

**Review by lsm5 — APPROVED** [review]
/lgtm
/hold

**Comment by cevich** [comment]
From the logs:

`fedora-podman-py:   Installing       : podman-5:4.4.0-1.fc37.x86_64                       189/214`

**Pull request merged**
