### PR TITLE
add compose to fedora

### PR DESCRIPTION
**Pull request by baude**
Signed-off-by: baude <bbaude@redhat.com>

### CODE REVIEW

**Review by edsantiago — APPROVED** [review]
LGTM

**Comment by cevich** [comment]
Hmmm, dunno why this PR didn't automatically merge (seems like it should have).  @baude want me to manually merge it?

**Comment by cevich** [comment]
OIC...the "commits must have verified [GPG] signatures" setting is turned on...

**Comment by cevich** [comment]
@Mergifyio refresh

**Comment by cevich** [comment]
c4704091098054656

**Pull request merged**
