### PR TITLE
Another bump, to pick up 6.11.6 kernel

### PR DESCRIPTION
**Pull request by edsantiago**
Also, bump pasta on f40 just to eliminate all chances
of podman flake 24219.
    
Also, add a simplified README explaining the usual-case
actions in this repo.

Signed-off-by: Ed Santiago <santiago@redhat.com>

### CODE REVIEW

**Comment by edsantiago** [comment]
- 20241107t182823z-f41f40d13
- 20241106t163000z-f41f40d13 &#x21D1; (built in #392)

|  |*debian*|*prior-fedora*|*fedora*|*fedora-aws*|*rawhide*|
|----|----|----|----|----|----|
|*kernel*       | 6.11.6-1        | 6.8.5-301       | 6.11.6-300      | 6.11.6-300      | 6.12.0-0.rc6.20241105git2e1b3cc9d7f7.52 |
|               |                |                |                | 6.11.5-300&nbsp;&#x21D1; | 6.12.0-0.rc6.51&nbsp;&#x21D1; |
|*aardvark-dns* | 1.12.2-1        | 1.12.2-2        | 1.13.0-1        | 1.13.0-1        | 1.13.0-2        |
|               |                |                |                |                | 1.12.2-2&nbsp;&#x21D1; |
|*netavark*     | 1.12.1-3        | 1.12.2-1        | 1.13.0-1        | 1.13.0-1        | 1.13.0-2        |
|               |                |                |                |                | 1.12.2-1&nbsp;&#x21D1; |
|*slirp4netns*  | 1.2.1-1+b1      | 1.3.1-1         | 1.3.1-1         | 1.3.1-1         | 1.3.1-1         |
|               |                | 1.2.2-2&nbsp;&#x21D1; |                | 1.2.2-3&nbsp;&#x21D1; |                |
|*systemd*      | 257\~rc1-3      | 255.13-1        | 256.7-1         | 256.7-1         | 256.7-1         |
|               | 256.7-3&nbsp;&#x21D1; |                |                |                |                |

**Comment by edsantiago** [comment]
- 20241107t210000z-f41f40d13
- 20241106t163000z-f41f40d13 &#x21D1; (built in #392)

|  |*debian*|*prior-fedora*|*fedora*|*fedora-aws*|*rawhide*|
|----|----|----|----|----|----|
|*kernel*       | 6.11.6-1        | 6.8.5-301       | 6.11.6-300      | 6.11.6-300      | 6.12.0-0.rc6.20241105git2e1b3cc9d7f7.52 |
|               |                |                |                | 6.11.5-300&nbsp;&#x21D1; | 6.12.0-0.rc6.51&nbsp;&#x21D1; |
|*aardvark-dns* | 1.12.2-1        | 1.12.2-2        | 1.13.0-1        | 1.13.0-1        | 1.13.0-2        |
|               |                |                |                |                | 1.12.2-2&nbsp;&#x21D1; |
|*netavark*     | 1.12.1-3        | 1.12.2-1        | 1.13.0-1        | 1.13.0-1        | 1.13.0-2        |
|               |                |                |                |                | 1.12.2-1&nbsp;&#x21D1; |
|*passt*        | 2024-10-30      | 2024-10-30      | 2024-10-30      | 2024-10-30      | 2024-10-30      |
|               |                | 2024-09-06&nbsp;&#x21D1; |                |                |                |
|*slirp4netns*  | 1.2.1-1+b1      | 1.3.1-1         | 1.3.1-1         | 1.3.1-1         | 1.3.1-1         |
|               |                | 1.2.2-2&nbsp;&#x21D1; |                | 1.2.2-3&nbsp;&#x21D1; |                |
|*systemd*      | 257\~rc1-3      | 255.13-1        | 256.7-1         | 256.7-1         | 256.7-1         |
|               | 256.7-3&nbsp;&#x21D1; |                |                |                |                |

**Comment by edsantiago** [comment]
Now merged in [podman](https://github.com/containers/podman/pull/24500) and [buildah](https://github.com/containers/buildah/pull/5833).

I think this might be a good candidate for tagging.

**Comment by Luap99** [comment]
yes sure, let's get the f41 bump into the other repos

**Pull request merged**
