### PR TITLE
Semiregular VM catchup

### PR DESCRIPTION
**Pull request by edsantiago**
- rawhide now includes rpm-plugin-ima, which breaks rootless
  podman pods. Add a timebomb'ed workaround until there's a
  more definitive solution in podman or its containers-* libraries

- bug fix for Makefile, handle indented timebombs

- install composefs in rawhide

Signed-off-by: Ed Santiago <santiago@redhat.com>

### CODE REVIEW

**Comment by edsantiago** [comment]
Comparing against what's currently in podman:

- 20240620t153000z-f40f39d13
- 20240529t141726z-f40f39d13 &#x21D1; (built in #338)

|  |*debian*|*prior-fedora*|*fedora*|*fedora-aws*|*rawhide*|
|----|----|----|----|----|----|
|*base*         | 13.3            | 39-1.5          | Generic         | ?               | 41-0            |
|               | 13.2&nbsp;&#x21D1; |                |                |                |                |
|*kernel*       | 6.8.12-1        | 6.9.4-100       | 6.9.5-200       | 6.9.4-200       | 6.8.5-301       |
|               | 6.8.11-1&nbsp;&#x21D1; | 6.8.10-200&nbsp;&#x21D1; | 6.8.5-301&nbsp;&#x21D1; | 6.8.5-301&nbsp;&#x21D1; | 6.9.0-64&nbsp;&#x21D1; |
|*grub2-common* | 2.12-2          | 2.06-120        | 2.06-123        | 2.06-123        | 2.06-123        |
|               |                |                | 2.06-121&nbsp;&#x21D1; | 2.06-121&nbsp;&#x21D1; | 2.06-121&nbsp;&#x21D1; |
|*aardvark-dns* | 1.4.0-5.1       | 1.11.0-1        | 1.11.0-1        | 1.11.0-1        | 1.11.0-1        |
|               |                | 1.10.0-1&nbsp;&#x21D1; | 1.10.0-1&nbsp;&#x21D1; | 1.10.0-1&nbsp;&#x21D1; | 1.10.0-1&nbsp;&#x21D1; |
|*netavark*     | 1.4.0-4.1       | 1.11.0-1        | 1.11.0-1        | 1.11.0-1        | 1.10.3-3        |
|               |                | 1.10.3-1&nbsp;&#x21D1; | 1.10.3-3&nbsp;&#x21D1; | 1.10.3-3&nbsp;&#x21D1; |                |
|*buildah*      | 1.33.7+ds1-1    | 1.35.4-1        | 1.36.0-1        | 1.35.4-1        | 1.36.0-1        |
|               |                |                |                |                | 1.35.4-1&nbsp;&#x21D1; |
|*conmon*       | 2.1.10+ds1-1+b1 | 2.1.12-1        | 2.1.12-1        | 2.1.10-1        | 2.1.10-1        |
|               |                | 2.1.10-1&nbsp;&#x21D1; |                |                |                |
|*container-selinux*| ?               | 2.231.0-1       | 2.232.1-1       | 2.232.1-1       | 2.232.1-1       |
|               |                |                | 2.231.0-1&nbsp;&#x21D1; | 2.231.0-1&nbsp;&#x21D1; | 2.231.0-6&nbsp;&#x21D1; |
|*containers-common*| ?               | 1-99            | 0.59.1-2        | 0.59.1-2        | 0.59.1-1        |
|               |                |                | 0.59.0-1&nbsp;&#x21D1; | 0.58.0-2&nbsp;&#x21D1; | 0.59.0-1&nbsp;&#x21D1; |
|*criu*         | 3.17.1-3        | 3.19-2          | 3.19-4          | 3.19-4          | 3.19-5          |
|               |                |                |                |                | 3.19-4&nbsp;&#x21D1; |
|*crun*         | 1.15-1          | 1.15-1          | 1.15-1          | 1.15-1          | 1.15-1          |
|               |                |                |                |                |                |
|*docker-ce*    | 5:26.1.4-1~debian.12~bookworm | ?               | ?               | ?               | ?               |
|               | 5:26.1.3-1~debian.12~bookworm&nbsp;&#x21D1; |                |                |                |                |
|*golang*       | 2:1.22~3        | 1.21.11-1       | 1.22.4-1        | 1.22.4-1        | 1.22.4-3        |
|               |                | 1.21.10-1&nbsp;&#x21D1; | 1.22.3-1&nbsp;&#x21D1; | 1.22.3-1&nbsp;&#x21D1; | 1.22.3-1&nbsp;&#x21D1; |
|*gvisor-tap-vsock*| ?               | 0.7.3-1         | 0.7.3-2         | 0.7.3-2         | 0.7.3-2         |
|               |                |                |                |                |                |
|*nmap-ncat*    | 7.94+git20230807.3be01efb1+dfsg-4 | 7.95-1          | 7.95-1          | 7.95-1          | 7.95-1          |
|               | 7.94+git20230807.3be01efb1+dfsg-3+b1&nbsp;&#x21D1; |                |                |                |                |
|*passt*        | 2024-06-07      | 2024-05-10      | 2024-06-07      | 2024-06-07      | 2024-06-07      |
|               | 2024-04-26&nbsp;&#x21D1; |                | 2024-05-10&nbsp;&#x21D1; | 2024-05-10&nbsp;&#x21D1; | 2024-05-23&nbsp;&#x21D1; |
|*podman*       | 4.9.4+ds1-1     | 4.9.4-1         | 5.1.1-1         | 5.1.1-1         | 5.0.3-1         |
|               |                |                | 5.1.0~rc1-1&nbsp;&#x21D1; | 5.0.3-1&nbsp;&#x21D1; |                |
|*runc*         | 1.1.12+ds1-2    | 1.1.12-1        | 1.1.12-3        | 1.1.12-3        | 1.1.12-3        |
|               |                |                |                |                |                |
|*skopeo*       | 1.13.3+ds1-2+b1 | 1.15.1-1        | 1.15.1-1        | 1.15.1-1        | 1.15.1-1        |
|               |                | 1.15.0-1&nbsp;&#x21D1; |                | 1.15.0-1&nbsp;&#x21D1; |                |
|*slirp4netns*  | 1.2.1-1+b1      | 1.2.2-1         | 1.2.2-2         | 1.2.2-2         | 1.2.2-2         |
|               |                |                |                |                |                |
|*systemd*      | 256.1-1         | 254.13-1        | 255.7-1         | 255.7-1         | 256.1-3         |
|               | 256~rc3-5&nbsp;&#x21D1; | 254.12-1&nbsp;&#x21D1; |                |                | 256~rc3-1&nbsp;&#x21D1; |
|*tar*          | 1.34+dfsg-1.2+deb12u1 | 1.35-2          | 1.35-3          | 1.35-3          | 1.35-3          |
|               |                |                |                |                |                |

**Comment by edsantiago** [comment]
Successful in [podman](https://github.com/containers/podman/pull/23058) and [buildah](https://github.com/containers/buildah/pull/5600)

**Comment by edsantiago** [comment]
@containers/podman-maintainers, @containers/buildah-maintainers PTAL. This is low risk. Brings in a new debian systemd needed on podman (https://github.com/containers/podman/pull/23020)

**Comment by Luap99** [comment]
Not an expert on the repo but changes looked simple enough so I merged it.

**Pull request merged**
