### PR TITLE
Remove unused packages and update python versions

### PR DESCRIPTION
**Pull request by inknos**
python-xdg was removed as a dependency
https://github.com/containers/podman-py/commit/8d1020ecc88c55890ce0e1fa843803247911df0b

tests are currently done for py12
https://github.com/containers/podman-py/commit/330cf0b5011a114d0bc4e86477e4e5c868dbad31

### CODE REVIEW

**Comment by cevich** [comment]
Hrmm, seems like you did things correctly, checking why it failed.

Also FYI: If you force-push/cancel any running VM build tasks are still running, they sometimes (annoyingly/unfortunately) leave behind running VMs that need to be manually cleaned up.  If it happens now/again it's fine, just letting you know.

**Comment by cevich** [comment]
I re-ran the two failed container image build tasks.  They failed due to a quay.io flake:

"Error: writing blob: initiating layer upload to /v2/libpod/ccia/blobs/uploads/ in quay.io: received unexpected HTTP status: 502 Bad Gateway"

This has been a long-term issue others on the team are very familiar with.

**Comment by edsantiago** [comment]
- 20240814t130155z-f40f39d13
- 20240805t173227z-f40f39d13 &#x21D1; (built in #371)

|  |*debian*|*prior-fedora*|*fedora*|*fedora-aws*|*rawhide*|
|----|----|----|----|----|----|
|*kernel*       | 6.10.4-1        | 6.5.6-300       | 6.8.5-301       | 6.8.5-301       | 6.8.5-301       |
|               | 6.9.12-1&nbsp;&#x21D1; | 6.9.12-100&nbsp;&#x21D1; | 6.9.12-200&nbsp;&#x21D1; | 6.9.12-200&nbsp;&#x21D1; |                |
|*grub2-common* | 2.12-5          | 2.06-121        | 2.06-123        | 2.06-123        | 2.12-4          |
|               |                |                |                |                | 2.06-124&nbsp;&#x21D1; |
|*aardvark-dns* | 1.9.0-2         | 1.11.0-1        | 1.12.1-1        | 1.12.1-1        | 1.12.1-1        |
|               | 1.6.0-3&nbsp;&#x21D1; |                |                | 1.11.0-3&nbsp;&#x21D1; |                |
|*netavark*     | 1.9.0-4         | 1.11.0-1        | 1.12.1-1        | 1.12.1-1        | 1.12.1-1        |
|               | 1.6.0-2.1&nbsp;&#x21D1; |                |                | 1.11.0-3&nbsp;&#x21D1; | 1.11.0-3&nbsp;&#x21D1; |
|*buildah*      | 1.35.3+ds1-3+b1 | 1.37.0-1        | 1.37.0-1        | 1.37.0-1        | 1.37.0-1        |
|               | 1.35.3+ds1-3&nbsp;&#x21D1; | 1.36.0-1&nbsp;&#x21D1; |                | 1.36.0-1&nbsp;&#x21D1; |                |
|*containers-common*| ?               | 1-99            | 0.60.1-1        | 0.60.0-1        | 0.60.1-1        |
|               |                |                | 0.60.0-1&nbsp;&#x21D1; |                | 0.60.0-1&nbsp;&#x21D1; |
|*crun*         | 1.16-1          | 1.15-1          | 1.15-1          | 1.15-1          | 1.15-2          |
|               | 1.15-1&nbsp;&#x21D1; |                |                |                |                |
|*docker-ce*    | 5:27.1.2-1\~debian.12\~bookworm | ?               | ?               | ?               | ?               |
|               | 5:27.1.1-1\~debian.12\~bookworm&nbsp;&#x21D1; |                |                |                |                |
|*gvisor-tap-vsock*| ?               | 0.7.4-1         | ?               | ?               | ?               |
|               |                | 0.7.3-1&nbsp;&#x21D1; |                |                |                |
|*passt*        | 2024-08-06      | 2024-06-24      | 2024-08-06      | 2024-08-06      | 2024-08-06      |
|               | 2024-07-26&nbsp;&#x21D1; |                | 2024-07-26&nbsp;&#x21D1; | 2024-06-24&nbsp;&#x21D1; | 2024-07-26&nbsp;&#x21D1; |
|*podman*       | 5.0.3+ds1-5+b2  | 4.9.4-1         | 5.2.0-1         | 5.2.0-1         | 5.2.0-1         |
|               | 5.0.3+ds1-5&nbsp;&#x21D1; |                |                | 5.1.2-1&nbsp;&#x21D1; | 5.2.0\~rc2-1&nbsp;&#x21D1; |
|*runc*         | 1.1.12+ds1-2+b1 | 1.1.12-1        | 1.1.12-3        | 1.1.12-3        | 1.1.12-4        |
|               | 1.1.12+ds1-2&nbsp;&#x21D1; |                |                |                |                |
|*skopeo*       | 1.13.3+ds1-2+b2 | 1.15.2-1        | 1.16.0-1        | 1.15.2-1        | 1.16.0-1        |
|               | 1.13.3+ds1-2+b1&nbsp;&#x21D1; |                |                |                |                |
|*systemd*      | 256.4-3         | 254.16-1        | 255.10-3        | 255.10-3        | 256.4-1         |
|               | 256.4-2&nbsp;&#x21D1; |                | 255.10-1&nbsp;&#x21D1; | 255.10-1&nbsp;&#x21D1; |                |

**Comment by edsantiago** [comment]
@inknos are you familiar with protocols here? Will you be following up with podman/buildah/etc test PRs?

**Comment by cevich** [comment]
I met with him the other day, he's going to need some guidance.  My understanding is the intent is to use the new fedora-podman-py image in the podman-py repo.  Though testing elsewhere won't hurt anything, I think his plans are bigger than just the image.

**Review by cevich — APPROVED** [review]
LGTM

**Comment by inknos** [comment]
@edsantiago if you would help me out taking over from where we stopped with Chris I would be glad to learn the process and open the PRs

**Comment by edsantiago** [comment]
It's easy! At least in theory. It's also tedious.

1. Go to whichever repo is most at risk by this change. Typically that's `podman`, but in this case Chris says you intend this for `podman-py` so that could be a good starting point. Also, `docker` changed, so you'll need to test this on `buildah`.
2. Edit `.cirrus.yml`. Search for `c202`. Replace that entire string with the `c202` string from this PR.
3. Submit a PR to that repo with only that change.
4. See what breaks. Please feel free to ask for help -- this part of the process can take days to resolve.

HTH

**Comment by inknos** [comment]
I am rebasing this and trying to make it work now that tests for podman-py are green again

**Comment by edsantiago** [comment]
- 20240919t145433z-f40f39d13
- 20240911t151000z-f40f39d13 &#x21D1; (built in #386)

|  |*debian*|*prior-fedora*|*fedora*|*fedora-aws*|*rawhide*|
|----|----|----|----|----|----|
|*grub2-common* | 2.12-5          | 2.06-121        | 2.06-123        | 2.06-123        | 2.12-7          |
|               |                |                |                |                | 2.12-4&nbsp;&#x21D1; |
|*buildah*      | 1.37.2+ds1-3    | 1.37.1-1        | 1.37.1-1        | 1.37.1-1        | 1.37.2-2        |
|               |                |                |                |                | 1.37.2-1&nbsp;&#x21D1; |
|*conmon*       | 2.1.10+ds1-1+b1 | 2.1.12-1        | 2.1.12-2        | 2.1.12-2        | 2.1.12-3        |
|               |                |                |                |                | 2.1.12-2&nbsp;&#x21D1; |
|*container-selinux*| ?               | 2.232.1-1       | 2.233.0-1       | 2.233.0-1       | 2.233.0-1       |
|               |                |                | 2.232.1-1&nbsp;&#x21D1; | 2.232.1-1&nbsp;&#x21D1; | 2.232.1-2&nbsp;&#x21D1; |
|*golang*       | 2:1.23\~2       | 1.21.12-1       | 1.22.7-1        | 1.22.7-1        | 1.23.1-1        |
|               | 2:1.22\~3&nbsp;&#x21D1; |                | 1.22.6-1&nbsp;&#x21D1; | 1.22.6-1&nbsp;&#x21D1; | 1.23.0-2&nbsp;&#x21D1; |
|*gvisor-tap-vsock*| ?               | 0.7.5-1         | ?               | ?               | ?               |
|               |                | 0.7.4-1&nbsp;&#x21D1; |                |                |                |
|*podman*       | 5.2.2+ds1-4     | 4.9.4-1         | 5.2.2-1         | 5.2.2-1         | 5.2.2-2         |
|               | 5.2.2+ds1-2&nbsp;&#x21D1; |                |                |                | 5.2.2-1&nbsp;&#x21D1; |
|*runc*         | 1.1.12+ds1-5+b1 | 1.1.12-1        | 1.1.12-3        | 1.1.12-3        | 1.1.12-4        |
|               | 1.1.12+ds1-5&nbsp;&#x21D1; |                |                |                |                |
|*skopeo*       | 1.16.1+ds1-1    | 1.16.1-1        | 1.16.1-1        | 1.16.1-1        | 1.16.1-2        |
|               | 1.13.3+ds1-2+b2&nbsp;&#x21D1; |                |                |                | 1.16.1-1&nbsp;&#x21D1; |
|*systemd*      | 256.6-1         | 254.16-1        | 255.12-1        | 255.12-1        | 256.5-1         |
|               |                |                | 255.10-3&nbsp;&#x21D1; | 255.10-3&nbsp;&#x21D1; |                |

**Comment by edsantiago** [comment]
@inknos what is the status of these images? Have you been able to test them?

**Comment by inknos** [comment]
@edsantiago unfortunately I can't figure out why the tests in the [PR](https://github.com/containers/podman-py/pull/430) seem broken. Could you help me with that?

**Comment by edsantiago** [comment]
@inknos ping, what is the status of this PR?

**Comment by edsantiago** [comment]
- 20241015t085508z-f40f39d13
- 20241010t105554z-f40f39d13 &#x21D1; (built in #387)

|  |*debian*|*prior-fedora*|*fedora*|*fedora-aws*|*rawhide*|
|----|----|----|----|----|----|
|*grub2-common* | 2.12-5          | 2.06-121        | 2.06-123        | 2.06-123        | 2.12-9          |
|               |                |                |                |                | 2.12-7&nbsp;&#x21D1; |
|*criu*         | 3.17.1-3        | 4.0-1           | 4.0-1           | 4.0-1           | 4.0-1           |
|               |                | 3.19-2&nbsp;&#x21D1; |                | 3.19-4&nbsp;&#x21D1; |                |
|*golang*       | 2:1.23\~2       | 1.22.8-1        | 1.22.7-1        | 1.22.7-1        | 1.23.2-2        |
|               |                | 1.22.7-3&nbsp;&#x21D1; |                |                |                |
|*systemd*      | 256.7-1         | 254.18-1        | 255.13-1        | 255.13-1        | 256.7-1         |
|               |                |                | 255.12-1&nbsp;&#x21D1; | 255.12-1&nbsp;&#x21D1; | 256.5-1&nbsp;&#x21D1; |

**Comment by inknos** [comment]
Done. I agree, this should only touch python, so podman-py is the only one affected

**Comment by edsantiago** [comment]
OK, good. But criu and systemd changed, and criu is a known-bad version, so please also submit a podman PR changing the `c2024` string. Be sure to cross-reference to this PR and back; see #23706 for a trivial example. If you're very lucky, the `c2024` change is the only one you will need to make.

**Comment by inknos** [comment]
Testing prs open:

https://github.com/containers/podman-py/pull/430

https://github.com/containers/podman/pull/24270

**Comment by edsantiago** [comment]
podman-py and podman PRs passed and merged.

**Pull request merged**
