### PR TITLE
Move win instance to faster storage and 6k iops

### PR DESCRIPTION
**Pull request by n1hility**

### CODE REVIEW

**Comment by edsantiago** [comment]
|*Distro*|*base*|*aardvark-dns*|*buildah*|*conmon*|
|-----|----|----|----|----|
|*debian*| 13 | 1.4.0-5 | 1.32.2+ds1-1 | 2.1.6+ds1-1 |
|*prior-fedora*| 38-1.6 | - | 1.33.2-1 | 2:2.1.7-2 |
|*fedora*| 39-1.5 | 1.9.0-1 | 1.33.2-1 | 2:2.1.8-2 |
|*fedora-aws*| - | 1.8.0-1 | 1.33.2-1 | 2:2.1.8-2 |
|*rawhide*| 40-0 | 1.9.0-1 | 1.33.2-1 | 2:2.1.8-2 |

|*Distro*|*container-selinux*|*containers-common*|*criu*|*crun*|
|-----|----|----|----|----|
|*debian*| - | - | 3.17.1-3 | 1.12-1 |
|*prior-fedora*| 2:2.224.0-1 | 4:1-89 | 3.18-1 | 1.12-1 |
|*fedora*| 2:2.226.0-1 | 4:1-95 | 3.19-2 | 1.12-1 |
|*fedora-aws*| 2:2.226.0-1 | 4:1-95 | 3.19-2 | 1.12-1 |
|*rawhide*| 2:2.226.0-1 | 4:1-100 | 3.19-2 | 1.12-1 |

|*Distro*|*golang*|*netavark*|*passt*|*podman*|
|-----|----|----|----|----|
|*debian*| 2:1.21~2 | 1.4.0-4 | 0.0~git20231107.74e6f48-1 | 4.7.2+ds1-2 |
|*prior-fedora*| 1.20.11-1 | - | 0^20231107.g56d9f6d-1 | 5:4.7.2-1 |
|*fedora*| 1.21.4-1 | 1.9.0-1 | - | 5:4.8.1-1 |
|*fedora-aws*| 1.21.4-1 | 1.8.0-2 | 0^20231119.g4f1709d-1 | 5:4.8.1-1 |
|*rawhide*| 1.21.5-1 | 1.9.0-1 | 0^20231204.gb86afe3-1 | 5:4.8.1-1 |

|*Distro*|*runc*|*skopeo*|*slirp4netns*|*systemd-container*|
|-----|----|----|----|----|
|*debian*| 1.1.10+ds1-1 | 1.13.3+ds1-2 | 1.2.1-1 | 255-1 |
|*prior-fedora*| 2:1.1.8-1 | 1:1.14.0-1 | 1.2.2-1 | 253.13-1 |
|*fedora*| 2:1.1.8-1 | 1:1.14.0-1 | 1.2.2-1 | 254.7-1 |
|*fedora-aws*| 2:1.1.8-1 | 1:1.14.0-1 | 1.2.2-1 | 254.7-1 |
|*rawhide*| 2:1.1.9-1 | 1:1.14.0-1 | 1.2.2-1 | 255-1 |

**Comment by rhatdan** [comment]
LGTM
/approve

**Comment by cevich** [comment]
@edsantiago I know we're "waiting" for a slew(?) of version bumps.  I have no idea which or where they are needed.  In your opinion, are these images "safe" to release for renovate to propose on all repos?  Or should I hold off until next year?

**Comment by edsantiago** [comment]
These images are already in use on podman (99%). the only difference is the `win` change. Yes, it's safe.

**Comment by cevich** [comment]
Thanks Ed.

**Comment by edsantiago** [comment]
EXPERIMENTAL: revert back to distro columns, package rows.

This was the way I first wrote my table. I moved to the other way (above) because:
* pasta versions are WAY too long, requiring horizontal scrolling, which is user-hostile
* what I'm usually interested in is comparing package versions across distros (like, "make sure everyone has crun 1.12") and that's generally easier when scanning vertically.

But I don't think the above multi-table form is all that easy to read. Like, slirp, there's a difference but it's subtle no matter how you look at the table. So here's a different rendering, and I'll keep both code paths for a while and will see which one looks better over time.

Feedback welcome.

|  |*debian*|*prior-fedora*|*fedora*|*fedora-aws*|*rawhide*|
|----|----|----|----|----|----|
|*base*| 13 | 38-1.6 | 39-1.5 | - | 40-0 |
|*aardvark-dns*| 1.4.0-5 | - | 1.9.0-1 | 1.8.0-1 | 1.9.0-1 |
|*buildah*| 1.32.2+ds1-1 | 1.33.2-1 | 1.33.2-1 | 1.33.2-1 | 1.33.2-1 |
|*conmon*| 2.1.6+ds1-1 | 2:2.1.7-2 | 2:2.1.8-2 | 2:2.1.8-2 | 2:2.1.8-2 |
|*container-selinux*| - | 2:2.224.0-1 | 2:2.226.0-1 | 2:2.226.0-1 | 2:2.226.0-1 |
|*containers-common*| - | 4:1-89 | 4:1-95 | 4:1-95 | 4:1-100 |
|*criu*| 3.17.1-3 | 3.18-1 | 3.19-2 | 3.19-2 | 3.19-2 |
|*crun*| 1.12-1 | 1.12-1 | 1.12-1 | 1.12-1 | 1.12-1 |
|*golang*| 2:1.21~2 | 1.20.11-1 | 1.21.4-1 | 1.21.4-1 | 1.21.5-1 |
|*netavark*| 1.4.0-4 | - | 1.9.0-1 | 1.8.0-2 | 1.9.0-1 |
|*passt*| 2023-11-07 | 2023-11-07 | - | 2023-11-19 | 2023-12-04 |
|*podman*| 4.7.2+ds1-2 | 5:4.7.2-1 | 5:4.8.1-1 | 5:4.8.1-1 | 5:4.8.1-1 |
|*runc*| 1.1.10+ds1-1 | 2:1.1.8-1 | 2:1.1.8-1 | 2:1.1.8-1 | 2:1.1.9-1 |
|*skopeo*| 1.13.3+ds1-2 | 1:1.14.0-1 | 1:1.14.0-1 | 1:1.14.0-1 | 1:1.14.0-1 |
|*slirp4netns*| 1.2.1-1 | 1.2.2-1 | 1.2.2-1 | 1.2.2-1 | 1.2.2-1 |
|*systemd-container*| 255-1 | 253.13-1 | 254.7-1 | 254.7-1 | 255-1 |

(This code path requires truncating pasta versions to just Y-M-D, which in some corner cases may not be unambiguous)

**Comment by cevich** [comment]
Looks good to me.  I had a thought over the holiday break on a possible way to get this data out at build time and save it as an artifact along with the `manifest.json`.  I haven't looked at the details yet, but I seem to remember there's a "run a local command" thing in packer.  Maybe the command could be `scp packer@1.2.3.4:/path/to/packages.txt ./`.  I'll go poking around the docs later to see if that's possible.

**Pull request merged**
