### PR TITLE
Enlarge fedora VM starting disk

### PR DESCRIPTION
**Pull request by cevich**
Provide more disk space for podman's static-build task cache-restoration.

### CODE REVIEW

**Comment by cevich** [comment]
@lsm5 PTAL when you get a sec.  The commit message has more detail than the PR description :wink:

**Comment by cevich** [comment]
@lsm5 un-poke.   Should have run this through the podman tests first.  There's some strange problem with the new images.

**Comment by cevich** [comment]
note to me: https://cirrus-ci.com/task/6194088208760832

**Comment by cevich** [comment]
note to me: diskspace / cache problem is fixed:

**Comment by cevich** [comment]
Testing this in: https://github.com/containers/podman/pull/8074 and https://github.com/containers/podman/pull/8107

**Comment by cevich** [comment]
This is working now.

**Comment by cevich** [comment]
@lsm5 PTAL, just is just for F33...an "accept" github review will cause this to merge.

**Review by lsm5 — APPROVED** [review]
LGTM

**Pull request merged**
