### PR TITLE
Makefile: build fedora_podman for both amd64 and arm64

### PR DESCRIPTION
**Pull request by lsm5**
Signed-off-by: Lokesh Mandvekar <lsm5@fedoraproject.org>

@cevich PTAL

### CODE REVIEW

**Comment by lsm5** [comment]
i'm hoping the failed jobs were just a timing mismatch between submitting PR and adding labels.

**Comment by lsm5** [comment]
@cevich looks like `qemu-user-static` is the missing piece that's causing the arm64 failure. I'm still looking for the right repo on c8s that'll get me that package

**Comment by lsm5** [comment]
@cevich and looks like `qemu-user-static` is not shipped on c8s. So, I guess it's either c9s or fedora at this point, wdyt?

**Comment by nalind** [comment]
You're probably going to want to replace `-t $*_podman:$(call err_if_empty,IMG_SFX)` with `--manifest $*_podman:$(call err_if_empty,IMG_SFX)` to put the built images into a manifest list instead of trying to tag both of them with the same name, which isn't possible.  I don't know if `podman save` will handle that, though.

**Comment by cevich** [comment]
> You're probably going to want to replace -t ...with...

Also good advise.  Though lots of other things use that podman build Makefile recipe, and expect regular images.  Hrmmm, I guess lets see when you get that far.

**Comment by nalind** [comment]
If there's no option that uses an RPM package that's part of the distribution, running
 `sudo podman run --net=host --rm --privileged multiarch/qemu-user-static -p yes`
or some equivalent should work approximately as well, if SELinux isn't going to prevent its binaries from interacting with binaries in other containers.

**Comment by lsm5** [comment]
@cevich shouldn't the new commit now run everything in `centos-stream-9` ? Re-running `Build fedora_podman container` with Terminal still shows me 
```
# cat /etc/centos-release 
CentOS Stream release 8
```

**Comment by cevich** [comment]
> shouldn't the new commit now run everything

Not everything, because the family name is used: https://github.com/containers/automation_images/blob/main/.cirrus.yml#L79

It's possible somebody else was running an image build in another PR, and so the "latest" image-builder VM wound up being theirs not yours.  However, use of the family name is necessary to support the `[CI:TOOLING]` feature :confounded:

Hmmm.  I'd suggest either making the update to C9s a separate PR, or using nalin's `multiarch/qemu-user-static` container suggestion.  I've done that before in different contexts, it works well (though it's confusing to understand *how* it works).  If disabling SELinux on the image-builder is needed, I'm fine with that.

**Comment by cevich** [comment]
Closing as "not being worked on".  Please re-open if that changes.

**Pull request closed without merging**
