### PR TITLE
add bpftrace for CI debugging

### PR DESCRIPTION
**Pull request by Luap99**
I like to run a bpftrace based program in CI to collect better logs for specific processes not observed in the normal testing such as the podman container cleanup command.

Given you need to have full privs to run ebpf and the package pulls in an entire toolchain which is almost 500MB in install size we do not add it the the container images to not bloat them without reason.

https://github.com/containers/podman/pull/23487

### CODE REVIEW

**Comment by edsantiago** [comment]
LGTM but you need to `make IMG_SFX`

**Comment by Luap99** [comment]
Right which greets me with
```
base_images/debian_base-setup.sh:52:timebomb 20240801 "prevent us from getting broken tar-1.35+dfsg-3"
cache_images/fedora_packaging.sh:220:    timebomb 20240710 "Temporary workaround for signed rpms (ima) in rawhide"
```

and I didn't really wanted to look at this right now. I guess I can just bump the time?

**Comment by edsantiago** [comment]
Yes, just bump it.

Note that there WILL be problems. It's been a month since my last `make` here, and it will probably take 3-6 iterations before this is ready. I will try my best to help.

**Comment by Luap99** [comment]
> Note that there WILL be problems

Yes I know that part... but I guess someone has to suffer through that no what what. Might as well be me.

**Comment by edsantiago** [comment]
- 20240805t173227z-f40f39d13
- 20240708t152000z-f40f39d13 &#x21D1; (built in #357)

|  |*debian*|*prior-fedora*|*fedora*|*fedora-aws*|*rawhide*|
|----|----|----|----|----|----|
|*base*         | 13.5            | 39-1.5          | Generic         | ?               | 41-0            |
|               | 13.3&nbsp;&#x21D1; |                |                |                |                |
|*kernel*       | 6.9.12-1        | 6.9.12-100      | 6.9.12-200      | 6.9.12-200      | 6.8.5-301       |
|               | 6.9.8-1&nbsp;&#x21D1; | 6.9.7-100&nbsp;&#x21D1; | 6.9.8-200&nbsp;&#x21D1; | 6.9.7-200&nbsp;&#x21D1; |                |
|*grub2-common* | 2.12-5          | 2.06-121        | 2.06-123        | 2.06-123        | 2.06-124        |
|               | 2.12-2&nbsp;&#x21D1; |                |                |                |                |
|*aardvark-dns* | 1.6.0-3         | 1.11.0-1        | 1.12.1-1        | 1.11.0-3        | 1.12.1-1        |
|               | 1.4.0-6&nbsp;&#x21D1; |                | 1.11.0-1&nbsp;&#x21D1; | 1.11.0-1&nbsp;&#x21D1; | 1.11.0-1&nbsp;&#x21D1; |
|*netavark*     | 1.6.0-2.1       | 1.11.0-1        | 1.12.1-1        | 1.11.0-3        | 1.11.0-3        |
|               | 1.4.0-4.1&nbsp;&#x21D1; |                | 1.11.0-1&nbsp;&#x21D1; | 1.11.0-1&nbsp;&#x21D1; | 1.11.0-1&nbsp;&#x21D1; |
|*buildah*      | 1.35.3+ds1-3    | 1.36.0-1        | 1.37.0-1        | 1.36.0-1        | 1.37.0-1        |
|               | 1.33.7+ds1-1&nbsp;&#x21D1; |                | 1.36.0-1&nbsp;&#x21D1; |                | 1.36.0-1&nbsp;&#x21D1; |
|*conmon*       | 2.1.10+ds1-1+b1 | 2.1.12-1        | 2.1.12-1        | 2.1.10-1        | 2.1.12-2        |
|               |                |                |                |                | 2.1.10-1&nbsp;&#x21D1; |
|*container-selinux*| ?               | 2.232.1-1       | 2.232.1-1       | 2.232.1-1       | 2.232.1-2       |
|               |                |                |                |                | 2.232.1-1&nbsp;&#x21D1; |
|*containers-common*| ?               | 1-99            | 0.60.0-1        | 0.60.0-1        | 0.60.0-1        |
|               |                |                | 0.59.1-2&nbsp;&#x21D1; | 0.59.1-2&nbsp;&#x21D1; | 0.59.1-1&nbsp;&#x21D1; |
|*criu*         | 3.17.1-3        | 3.19-2          | 3.19-6          | 3.19-4          | 3.19-7          |
|               |                |                | 3.19-4&nbsp;&#x21D1; |                | 3.19-5&nbsp;&#x21D1; |
|*crun*         | 1.15-1          | 1.15-1          | 1.15-1          | 1.15-1          | 1.15-2          |
|               |                |                |                |                | 1.15-1&nbsp;&#x21D1; |
|*docker-ce*    | 5:27.1.1-1\~debian.12\~bookworm | ?               | ?               | ?               | ?               |
|               | 5:27.0.3-1\~debian.12\~bookworm&nbsp;&#x21D1; |                |                |                |                |
|*golang*       | 2:1.22\~3       | 1.21.12-1       | 1.22.5-1        | 1.22.5-1        | 1.23\~rc2-1     |
|               |                | 1.21.11-1&nbsp;&#x21D1; | 1.22.4-1&nbsp;&#x21D1; | 1.22.4-1&nbsp;&#x21D1; | 1.23\~rc1-2&nbsp;&#x21D1; |
|*nmap-ncat*    | 7.94+git20230807.3be01efb1+dfsg-4 | 7.92-2          | 7.92-2          | 7.92-2          | 7.92-3          |
|               |                | 7.95-1&nbsp;&#x21D1; | 7.95-1&nbsp;&#x21D1; | 7.95-1&nbsp;&#x21D1; | 7.95-1&nbsp;&#x21D1; |
|*passt*        | 2024-07-26      | 2024-06-24      | 2024-07-26      | 2024-06-24      | 2024-07-26      |
|               | 2024-06-24&nbsp;&#x21D1; | 2024-06-07&nbsp;&#x21D1; | 2024-06-24&nbsp;&#x21D1; |                | 2024-06-24&nbsp;&#x21D1; |
|*podman*       | 5.0.3+ds1-5     | 4.9.4-1         | 5.2.0-1         | 5.1.2-1         | 5.2.0\~rc2-1    |
|               | 4.9.5+ds1-1&nbsp;&#x21D1; |                | 5.1.1-1&nbsp;&#x21D1; | 5.1.1-1&nbsp;&#x21D1; | 5.0.3-1&nbsp;&#x21D1; |
|*runc*         | 1.1.12+ds1-2    | 1.1.12-1        | 1.1.12-3        | 1.1.12-3        | 1.1.12-4        |
|               |                |                |                |                | 1.1.12-3&nbsp;&#x21D1; |
|*skopeo*       | 1.13.3+ds1-2+b1 | 1.15.2-1        | 1.16.0-1        | 1.15.2-1        | 1.16.0-1        |
|               |                | 1.15.1-1&nbsp;&#x21D1; | 1.15.1-1&nbsp;&#x21D1; | 1.15.1-1&nbsp;&#x21D1; | 1.15.1-1&nbsp;&#x21D1; |
|*slirp4netns*  | 1.2.1-1+b1      | 1.2.2-1         | 1.2.2-2         | 1.2.2-2         | 1.2.2-3         |
|               |                |                |                |                | 1.2.2-2&nbsp;&#x21D1; |
|*systemd*      | 256.4-2         | 254.16-1        | 255.10-1        | 255.10-1        | 256.4-1         |
|               | 256.2-1&nbsp;&#x21D1; | 254.14-1&nbsp;&#x21D1; | 255.8-1&nbsp;&#x21D1; | 255.8-1&nbsp;&#x21D1; | 256.1-8&nbsp;&#x21D1; |
|*tar*          | 1.34+dfsg-1.2+deb12u1 | 1.35-2          | 1.35-3          | 1.35-3          | 1.35-4          |
|               |                |                |                |                | 1.35-3&nbsp;&#x21D1; |

**Comment by edsantiago** [comment]
@Luap99 care to repush, to pick up new pasta? (https://github.com/containers/podman/issues/23478#issuecomment-2271646047)

**Comment by Luap99** [comment]
Shouldn't we merge this first as the images are now used in podman?

**Comment by Luap99** [comment]
Also do we actually get the packages from the testing repos here? I would assume we need to wait for it to hit stable, no?

**Comment by edsantiago** [comment]
Eek I missed that. Okay, merged. @baude your turn, please rebase and rerun `make IMG_SFX` and let's see how that goes.

**Pull request merged**
