### PR TITLE
Specify arm64 in relevant tasks for clarity

### PR DESCRIPTION
**Pull request by lsm5**
piggybacks on https://github.com/containers/automation_images/pull/143 

@cevich PTAL

### CODE REVIEW

**Review by cevich — APPROVED** [review]
LGTM.  Make sure you update the `no_*` labels before merging :smiley:

**Comment by lsm5** [comment]
> LGTM. Make sure you update the `no_*` labels before merging smiley

yes, updated just now. PTAL

**Comment by lsm5** [comment]
@cevich all green. Merging..

**Comment by lsm5** [comment]
@cevich ohh, I should have removed the labels before merging, right?

**Comment by cevich** [comment]
Nope (for the record) it's fine.  Nothing significant VM image wise happens on merge, it's all in PRs.  Only some container images are built on merge.

**Pull request merged**
